/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import schoolmgtsystem.dbhelper.DBHandler;
import schoolmgtsystem.model.UserResult;

/**
 *
 * @author FabulousTHO
 */
public class ExamResult extends javax.swing.JFrame {

    DBHandler handler;
    UserResult userResult;
//    String conStr = "jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=SchoolManagementSystem;user=sa;password=123456789";

    /**
     * Creates new form Multiple
     */
    public ExamResult() {
        initComponents();
    }

    //OverLoading Constructor
    public ExamResult(String getID) {
        initComponents();
        ShowStudentID.txtSID.setText(getID);
        txtStudentID.setText(getID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTranscript = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRanking = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtTotalScore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGovernment = new javax.swing.JTextField();
        txtChemistry = new javax.swing.JTextField();
        txtCommerce = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAccounting = new javax.swing.JTextField();
        txtEnglish = new javax.swing.JTextField();
        txtMaths = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBiology = new javax.swing.JTextField();
        txtGeography = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPhysics = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtArts = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtComputer = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFMaths = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtLit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtAgric = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCRS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtFrench = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtCivic = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtEcons = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "Result Printout", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        txtTranscript.setEditable(false);
        txtTranscript.setColumns(20);
        txtTranscript.setRows(5);
        jScrollPane1.setViewportView(txtTranscript);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 380, 490));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Surname", "Course Code", "Maths", "English", "Accounting", "Commerce", "Chemistry", "Government", "Biology", "Geography", "Physics", "Total Score", "Average", "Ranking"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1260, 100));

        btnRanking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRanking.setText("Ranking");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        jPanel4.add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        btnTranscript.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });
        jPanel4.add(btnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        btnRecord.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRecord.setText("Add Record");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });
        jPanel4.add(btnRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 130, 30));

        btnGenerate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel4.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, -1, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 610, -1, -1));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 610, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Left_30px_1.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "SENIOR SCHOOL RESULT RECORDS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 51, 107, -1));

        txtStudentID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtStudentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 48, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Full Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 107, -1));

        txtFirstName.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 270, -1));

        txtTotalScore.setEditable(false);
        txtTotalScore.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotalScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalScoreActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total Score");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 107, -1));

        txtAverage.setEditable(false);
        txtAverage.setBackground(new java.awt.Color(255, 255, 255));
        txtAverage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAverage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Average");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 107, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Chemistry");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 107, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Government");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        txtGovernment.setEditable(false);
        txtGovernment.setBackground(new java.awt.Color(255, 255, 255));
        txtGovernment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGovernment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtGovernment, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 90, -1));

        txtChemistry.setEditable(false);
        txtChemistry.setBackground(new java.awt.Color(255, 255, 255));
        txtChemistry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtChemistry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtChemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 90, -1));

        txtCommerce.setEditable(false);
        txtCommerce.setBackground(new java.awt.Color(255, 255, 255));
        txtCommerce.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCommerce.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCommerce, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Commerce");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 107, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Accounting");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 107, -1));

        txtAccounting.setEditable(false);
        txtAccounting.setBackground(new java.awt.Color(255, 255, 255));
        txtAccounting.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAccounting.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAccounting, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 90, -1));

        txtEnglish.setEditable(false);
        txtEnglish.setBackground(new java.awt.Color(255, 255, 255));
        txtEnglish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEnglish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 90, -1));

        txtMaths.setEditable(false);
        txtMaths.setBackground(new java.awt.Color(255, 255, 255));
        txtMaths.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMaths.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 90, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Maths");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 66, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("English");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 107, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 350, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Position");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 107, -1));

        txtPosition.setEditable(false);
        txtPosition.setBackground(new java.awt.Color(255, 255, 255));
        txtPosition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Biology");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        txtBiology.setEditable(false);
        txtBiology.setBackground(new java.awt.Color(255, 255, 255));
        txtBiology.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBiology.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBiology, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 90, -1));

        txtGeography.setEditable(false);
        txtGeography.setBackground(new java.awt.Color(255, 255, 255));
        txtGeography.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGeography.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGeography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographyActionPerformed(evt);
            }
        });
        jPanel1.add(txtGeography, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Geography");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        txtPhysics.setEditable(false);
        txtPhysics.setBackground(new java.awt.Color(255, 255, 255));
        txtPhysics.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPhysics.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPhysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 90, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Physics");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        txtArts.setEditable(false);
        txtArts.setBackground(new java.awt.Color(255, 255, 255));
        txtArts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtArts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtArts, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Fine Arts");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Computer");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));

        txtComputer.setEditable(false);
        txtComputer.setBackground(new java.awt.Color(255, 255, 255));
        txtComputer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtComputer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("F. Maths");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, -1));

        txtFMaths.setEditable(false);
        txtFMaths.setBackground(new java.awt.Color(255, 255, 255));
        txtFMaths.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFMaths.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtFMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Literature");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, -1));

        txtLit.setEditable(false);
        txtLit.setBackground(new java.awt.Color(255, 255, 255));
        txtLit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtLit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtLit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 90, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Agriculture");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 110, -1));

        txtAgric.setEditable(false);
        txtAgric.setBackground(new java.awt.Color(255, 255, 255));
        txtAgric.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAgric.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAgric, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 90, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("C R S");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 80, -1));

        txtCRS.setEditable(false);
        txtCRS.setBackground(new java.awt.Color(255, 255, 255));
        txtCRS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCRS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 90, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("French");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 80, -1));

        txtFrench.setEditable(false);
        txtFrench.setBackground(new java.awt.Color(255, 255, 255));
        txtFrench.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFrench.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtFrench, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 90, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Civic Education");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 120, -1));

        txtCivic.setEditable(false);
        txtCivic.setBackground(new java.awt.Color(255, 255, 255));
        txtCivic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCivic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCivic, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 90, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Economics");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, -1));

        txtEcons.setEditable(false);
        txtEcons.setBackground(new java.awt.Color(255, 255, 255));
        txtEcons.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEcons.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 90, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 810, 490));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        double[] R = new double[20];

        R[0] = Double.parseDouble(txtEnglish.getText());
        R[1] = Double.parseDouble(txtMaths.getText());
        R[2] = Double.parseDouble(txtCommerce.getText());
        R[3] = Double.parseDouble(txtEcons.getText());
        R[4] = Double.parseDouble(txtPhysics.getText());
        R[5] = Double.parseDouble(txtBiology.getText());
        R[6] = Double.parseDouble(txtAccounting.getText());
        R[7] = Double.parseDouble(txtFMaths.getText());
        R[8] = Double.parseDouble(txtLit.getText());
        R[9] = Double.parseDouble(txtGeography.getText());
        R[10] = Double.parseDouble(txtCRS.getText());
        R[11] = Double.parseDouble(txtGovernment.getText());
        R[12] = Double.parseDouble(txtChemistry.getText());
        R[13] = Double.parseDouble(txtAgric.getText());
        R[14] = Double.parseDouble(txtArts.getText());
        R[15] = Double.parseDouble(txtComputer.getText());
        R[16] = Double.parseDouble(txtFrench.getText());
        R[17] = Double.parseDouble(txtCivic.getText());

        R[18] = (R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7] + R[8] + R[9] + R[10] + R[11] + R[12] + R[13] + R[14]
                + R[15] + R[16] + R[17]) / 18;
        //R[9] = (R[0] + R[1] + R[2] + R[3] + R[5] + R[6] + R[7])/7;
        R[19] = R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7] + R[8] + R[9] + R[10] + R[11] + R[12] + R[13] + R[14]
                + R[15] + R[16] + R[17];

        String Average = String.format("%.0f", R[18]);
        txtAverage.setText(Average);

        String TotalScore = String.format("%.0f", R[19]);
        txtTotalScore.setText(TotalScore);

        if (R[19] >= 700) {
            txtPosition.setText("1st");
        } else if (R[19] >= 600) {
            txtPosition.setText("2nd");
        } else if (R[19] >= 500) {
            txtPosition.setText("3rd");
        } else if (R[19] >= 400) {
            txtPosition.setText("4th");
        } else if (R[19] >= 300) {
            txtPosition.setText("Average");
        } else if (R[19] >= 200) {
            txtPosition.setText("Fail");
        }
        //else if (R[10] >= 100){
        //txtRanking.setText("Poor");
        //}
        //else if (R[10] >= 50){
        // txtRanking.setText("Fail");
        //}

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            txtStudentID.getText(),
            txtFirstName.getText(),
//            txtSurname.getText(),
            //            txtCourseCode.getSelectedItem(),
            txtMaths.getText(),
            txtEnglish.getText(),
            txtAccounting.getText(),
            txtCommerce.getText(),
            txtChemistry.getText(),
            txtGovernment.getText(),
            txtBiology.getText(),
            txtGeography.getText(),
            txtPhysics.getText(),
            txtTotalScore.getText(),
            txtAverage.getText(),
            txtPosition.getText()
        });
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
        txtTranscript.append("Excel International School(To be great is our priority)"
                + "\n\tStudent Result"
                + "\n_____________________________________"
                + "\nStudent ID:\t\t" + txtStudentID.getText()
                + "\n_____________________________________"
                + "\nFirst Name:\t\t" + txtFirstName.getText()
//                + "\n_____________________________________"
//                + "\nSurname:\t\t" + txtSurname.getText()
//                + "\n_____________________________________"
                //                + "\nCourse Code:\t\t" + txtCourseCode.getSelectedItem()
                + "\n_____________________________________"
                + "\nMaths:\t\t" + txtMaths.getText()
                + "\n_____________________________________"
                + "\nEnglish:\t\t" + txtEnglish.getText()
                + "\n_____________________________________"
                + "\nAccounting:\t\t" + txtAccounting.getText()
                + "\n_____________________________________"
                + "\nCommerce:\t\t" + txtCommerce.getText()
                + "\n_____________________________________"
                + "\nChemistry:\t\t" + txtChemistry.getText()
                + "\n_____________________________________"
                + "\nGovernment:\t\t" + txtGovernment.getText()
                + "\n_____________________________________"
                + "\nBiology:\t\t" + txtBiology.getText()
                + "\n_____________________________________"
                + "\nGeography:\t\t" + txtGeography.getText()
                + "\n_____________________________________"
                + "\nPhysics:\t\t" + txtPhysics.getText()
                + "\n_____________________________________"
                + "\nTotal Score:\t\t" + txtTotalScore.getText()
                + "\n_____________________________________"
                + "\nAverage:\t\t" + txtAverage.getText()
                + "\n_____________________________________"
                + "\nPosition:\t\t" + txtPosition.getText()
                + "\n_____________________________________"
        );

    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed

        new ResultEntry().show();
        this.dispose();

    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        String str = "select * from sss where StudentID = ?";

        try {
            handler = new DBHandler();

            PreparedStatement pst = handler.getdbConnection().prepareStatement(str);

            pst.setString(1, txtStudentID.getText());

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {

                txtStudentID.setText(rs.getString("StudentID"));
                txtMaths.setText(rs.getString("Maths_Total"));
                txtEnglish.setText(rs.getString("English_Total"));
                txtLit.setText(rs.getString("Literature_Total"));
                txtCommerce.setText(rs.getString("Commerce_Total"));
                txtEcons.setText(rs.getString("Economics_Total"));
                txtPhysics.setText(rs.getString("Physics_Total"));
                txtBiology.setText(rs.getString("Biology_Total"));
                txtCivic.setText(rs.getString("Civic_Total"));
                txtCRS.setText(rs.getString("CRS_Total"));
                txtAccounting.setText(rs.getString("Account_Total"));
                txtFMaths.setText(rs.getString("FMaths_Total"));
                txtGeography.setText(rs.getString("Geography_Total"));
                txtAgric.setText(rs.getString("Agric_Total"));
                txtGovernment.setText(rs.getString("Government_Total"));
                txtChemistry.setText(rs.getString("Chemistry_Total"));
                txtArts.setText(rs.getString("Arts_Total"));
                txtComputer.setText(rs.getString("Computer_Total"));
                txtFrench.setText(rs.getString("French_Total"));

//                //txtEmail.setText(rs.getString("EmailAddress"));
//                txtStudentID.setText(rs.getString("StudentID"));
////                txtFirstName.setText(rs.getString("FirstName"));
////                txtSurname.setText(rs.getString("Surname"));
////                txtCourseCode.setSelectedItem(rs.getString("CourseCode"));
//                txtMaths.setText(rs.getString("Maths"));
//                txtEnglish.setText(rs.getString("English"));
//                txtAccounting.setText(rs.getString("Accounting"));
//                txtCommerce.setText(rs.getString("Commerce"));
//                txtChemistry.setText(rs.getString("Chemistry"));
//                txtGovernment.setText(rs.getString("Government"));
//                txtBiology.setText(rs.getString("Biology"));
//                txtGeography.setText(rs.getString("Geography"));
//                txtPhysics.setText(rs.getString("Physics"));
//                //txtTotalScore.setText(rs.getString("TotalScore"));
//                //txtAverage.setText(rs.getString("Average"));
//                //txtPosition.setText(rs.getString("Position"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentResult.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        JTextField temp = null;
        for (Component C : jPanel1.getComponents()) {
            if (C.getClass().toString().contains("javax.swing.JTextField")) {

                temp = (JTextField) C;
                temp.setText(null);

                JTextArea tem = null;
                for (Component A : jPanel1.getComponents()) {
                    if (A.getClass().toString().contains("javax.swing.JTextArea")) {

                        tem = (JTextArea) A;
                        tem.setText(null);
                    }
                    txtTranscript.setText("");
                }
            }
        }

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        int sel = JOptionPane.showConfirmDialog(this, "Do you want to print Result?");
        if (sel == 0) {
            try {
                printResult();
            } catch (IOException ex) {
                Logger.getLogger(ResultNursery.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (sel == 1) {
            this.show();
        }
        if (sel == 2) {
            this.show();
        }

    }//GEN-LAST:event_btnPrintActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        new ResultView().show();
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void txtTotalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalScoreActionPerformed

    private void txtGeographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeographyActionPerformed
    private JFrame frame;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ExamResult().setVisible(true);
        });
    }

//    public void insertDB() {
//
//        handler = new DBHandler();
//
//        String id = txtStudentID.getText();
////        String email = txtEmail.getText();
//        String firstname = txtFirstName.getText();
//        String surname = txtSurname.getText();
////        int coursecode = txtCourseCode.getSelectedIndex();
//        String maths = txtMaths.getText();
//        String english = txtEnglish.getText();
//        String account = txtAccounting.getText();
//        String commerce = txtCommerce.getText();
//        String chemis = txtChemistry.getText();
//        String gov = txtGovernment.getText();
//        String bio = txtBiology.getText();
//        String geo = txtGeography.getText();
//        String phy = txtPhysics.getText();
//
//        userResult = new UserResult(id, /*email,*/ firstname, surname, /*coursecode,*/ maths, english, account,
//                commerce, chemis, gov, bio, geo, phy);
//
//        handler.insertDB(userResult);
//
////        txtEmail.setText("");
//        txtFirstName.setText("");
//        txtSurname.setText("");
////        txtCourseCode.setSelectedIndex(0);
//        txtMaths.setText("");
//        txtEnglish.setText("");
//        txtAccounting.setText("");
//        txtCommerce.setText("");
//        txtChemistry.setText("");
//        txtGovernment.setText("");
//        txtBiology.setText("");
//        txtGeography.setText("");
//        txtPhysics.setText("");
//
//    }
    public void printResult() throws IOException {

        //PreparedStatement to get the 1st and 2nd Test score
        String str = "select * from sss where StudentID = ?";

        handler = new DBHandler();

        //Variables to reference Test and Exam from the Database
        String english1 = null, english2 = null, englishE = null, maths1 = null, maths2 = null, mathsE = null, crs1 = null,
                crs2 = null, crsE = null, civic1 = null, civic2 = null, civicE = null, ict1 = null, ict2 = null, ictE = null,
                econ1 = null, econ2 = null, econE = null, agric1 = null, agric2 = null, agricE = null, lit1 = null, lit2 = null,
                litE = null, art1 = null, art2 = null, artE = null, comm1 = null, comm2 = null, commE = null, fre1 = null, fre2 = null,
                freE = null, gov1 = null, gov2 = null, govE = null, phy1 = null, phy2 = null, phyE = null, chem1 = null, chem2 = null,
                chemE = null, geo1 = null, geo2 = null, geoE = null, acc1 = null, acc2 = null, accE = null, fmaths1 = null, fmaths2 = null,
                fmathsE = null, bio1 = null, bio2 = null, bioE = null;

        try {
            PreparedStatement pst = handler.getdbConnection().prepareStatement(str);

//             Statement pst = handler.getdbConnection().createStatement();
            pst.setString(1, txtStudentID.getText());

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                txtStudentID.setText(rs.getString("StudentID"));
                english1 = rs.getString("English1");
                english2 = rs.getString("English2");
                englishE = rs.getString("English_Exam");
                maths1 = rs.getString("Maths1");
                maths2 = rs.getString("Maths2");
                mathsE = rs.getString("Maths_Exam");
                crs1 = rs.getString("CRS1");
                crs2 = rs.getString("CRS2");
                crsE = rs.getString("CRS_Exam");
                fmaths1 = rs.getString("FMaths1");
                fmaths2 = rs.getString("FMaths2");
                fmathsE = rs.getString("FMaths_Exam");
                acc1 = rs.getString("Account1");
                acc2 = rs.getString("Account2");
                accE = rs.getString("Account_Exam");
                phy1 = rs.getString("Physics1");
                phy2 = rs.getString("Physics2");
                phyE = rs.getString("Physics_Exam");
                bio1 = rs.getString("Biology1");
                bio2 = rs.getString("Biology2");
                bioE = rs.getString("Biology_Exam");
                civic1 = rs.getString("Civic1");
                civic2 = rs.getString("Civic2");
                civicE = rs.getString("Civic_Exam");
                gov1 = rs.getString("Government1");
                gov2 = rs.getString("Government2");
                govE = rs.getString("Government_Exam");
                ict1 = rs.getString("Computer1");
                ict2 = rs.getString("Computer2");
                ictE = rs.getString("Computer_Exam");
                econ1 = rs.getString("Economics1");
                econ2 = rs.getString("Economics2");
                econE = rs.getString("Economics_Exam");
                agric1 = rs.getString("Agric1");
                agric2 = rs.getString("Agric2");
                agricE = rs.getString("Agric_Exam");
                lit1 = rs.getString("Literature1");
                lit2 = rs.getString("Literature2");
                litE = rs.getString("Literature_Exam");
                geo1 = rs.getString("Geography1");
                geo2 = rs.getString("Geography2");
                geoE = rs.getString("Geography_Exam");
                art1 = rs.getString("Arts1");
                art2 = rs.getString("Arts2");
                artE = rs.getString("Arts_Exam");
                comm1 = rs.getString("Commerce1");
                comm2 = rs.getString("Commerce2");
                commE = rs.getString("Commerce_Exam");
                chem1 = rs.getString("Chemistry1");
                chem2 = rs.getString("Chemistry2");
                chemE = rs.getString("Chemistry_Exam");
                fre1 = rs.getString("French1");
                fre2 = rs.getString("French2");
                freE = rs.getString("French_Exam");

            }

            System.out.println("1st Test " + english1);
            System.out.println("2st Test " + english2);
            System.out.println("Exam " + englishE);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ResultNursery.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Creating a file dialog with file chooser
        //Prints out file in PDF format
        JFileChooser chooser = new JFileChooser();
        chooser.showSaveDialog(this);
        chooser.getSelectedFile();

        File file = chooser.getSelectedFile();

        Document document = new Document();
        Font font = new Font();

        try {

            String school = "BRIGHT STARS SCHOOL";
            String slogan = "(NURSERY, PRIMARY & SECONDARY)";
            String address = "Omorodion Osaretin Str, Off Okuwague\nEvbabogun Road, Off Sapele Road, Benin City";
            String tel = "07067183000";
            String motto = "Knowledge for Excellence";

            String english_total = txtEnglish.getText();
            String maths_total = txtMaths.getText();
            String comm_total = txtCommerce.getText();
            String econ_total = txtEcons.getText();
            String phy_total = txtPhysics.getText();
            String bio_total = txtBiology.getText();
            String acc_total = txtAccounting.getText();
            String civic_total = txtCivic.getText();
            String fmaths_total = txtFMaths.getText();
            String lit_total = txtLit.getText();
            String geo_total = txtGeography.getText();
            String crs_total = txtCRS.getText();
            String gov_total = txtGovernment.getText();
            String chem_total = txtChemistry.getText();
            String agric_total = txtAgric.getText();
            String arts_total = txtArts.getText();
            String ict_total = txtComputer.getText();
            String fre_total = txtFrench.getText();
            String score_total = txtTotalScore.getText();
            String average_total = txtAverage.getText();
            String position_total = txtPosition.getText();

            System.out.println("English Total " + english_total);

            PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(file));
            document.open();

//            Paragraph ti = new Paragraph();
//            ti.add(school);
//            ti.setAlignment(Element.ALIGN_CENTER);
//            font = ti.getFont();
//
//            Paragraph sl = new Paragraph();
//            sl.add(slogan);
//            sl.setAlignment(Element.ALIGN_CENTER);
//            font = sl.getFont();
//            sl.setSpacingBefore(0);
//            font.setSize(8);
//
//            Paragraph sti = new Paragraph();
//            sti.add(address);
//            sti.setAlignment(Element.ALIGN_CENTER);
            Image image = Image.getInstance("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\SchoolMgtSystem\\Bright_Stars.png");
            image.setAbsolutePosition(70, 720);

            Font tiFont = new Font(Font.FontFamily.TIMES_ROMAN, 20, 20);
            Paragraph ti = new Paragraph();
            ti.add("BRIGHT STARS SENIOR SECONDARY SCHOOL");
            ti.setAlignment(Element.ALIGN_CENTER);
            ti.trimToSize();
            ti.setFont(tiFont);
            font = ti.getFont();
            ti.setSpacingAfter(20f);
            font.setColor(135, 198, 240);
//            font.setSize(30);

            Paragraph sl = new Paragraph();
            sl.add("(NURSERY, PRIMARY & SECONDARY)");
            sl.setAlignment(Element.ALIGN_CENTER);
            font = sl.getFont();
            sl.setSpacingAfter(20f);
            font.setColor(135, 198, 240);
            font.setSize(11);

            Paragraph sti = new Paragraph();
            sti.add("Omorodion Osaretin Str, Off Okuwague\nEvbabogun Road, Off Sapele Road, Benin City");
            sti.setAlignment(Element.ALIGN_CENTER);
            font = sti.getFont();
            font.setColor(135, 198, 240);

            Paragraph tele = new Paragraph();
            tele.add("Tel: 07067183000" + " \tEmail: informbrightstars@yahoo.com");
            tele.setAlignment(Element.ALIGN_CENTER);
            font = tele.getFont();
            font.setColor(135, 198, 240);

            Paragraph mot = new Paragraph();
            mot.add("MOTTO: Knowledge for Excellence");
            mot.setAlignment(Element.ALIGN_CENTER);
            font = mot.getFont();
            font.setColor(135, 198, 240);

            Paragraph name = new Paragraph();
            name.setAlignment(Element.ALIGN_CENTER);
            name.add("Full Name: ___________________________________" + txtFirstName.getText()
                    + "   Class: ________" + "   Term: ________");
            name.setSpacingBefore(7f);
            name.setSpacingAfter(10f);

//            Paragraph img = new Paragraph();
//            img.add(Image.getInstance("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\SchoolMgtSystem\\Bright_Stars.png"));
//            img.setAlignment(Element.ALIGN_CENTER);
            //Adding to the Document
            document.add(image);
            document.add(ti);
            document.add(sl);
            document.add(sti);
            document.add(tele);
            document.add(mot);
            document.add(name);

//            document.add(new Paragraph(subTitle));
//            document.add(new Paragraph("Student ID: " + txtStudentID.getText()));
//            document.add(new Paragraph("First Name: " + txtFirstName.getText()));
//            document.add(new Paragraph("Surname: " + txtSurname.getText()));
//            document.add(new Paragraph("Course Code: " + txtCourseCode.getSelectedItem()));
//            document.add(new Paragraph("DETAILED RESULT"));
            PdfPTable table = new PdfPTable(8);
            table.setWidthPercentage(105);
            table.setSpacingBefore(11f);
            table.setSpacingAfter(11f);

            float[] colWidth = {2f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f};
            table.setWidths(colWidth);

            PdfPCell c1 = new PdfPCell(new Paragraph(""));
            PdfPCell c2 = new PdfPCell(new Paragraph("1ST\nTEST"));
            PdfPCell c3 = new PdfPCell(new Paragraph("2ND\nTEST"));
            PdfPCell c4 = new PdfPCell(new Paragraph("EXAM"));
            PdfPCell c5 = new PdfPCell(new Paragraph("TOTAL"));
            PdfPCell c6 = new PdfPCell(new Paragraph("GRADE"));
            PdfPCell c7 = new PdfPCell(new Paragraph("POSITOIN"));
            PdfPCell c8 = new PdfPCell(new Paragraph("SIGN"));

            PdfPCell en1 = new PdfPCell(new Paragraph("ENGLISH LANGUAGE"));
            PdfPCell en2 = new PdfPCell(new Paragraph(english1));
            PdfPCell en3 = new PdfPCell(new Paragraph(english2));
            PdfPCell en4 = new PdfPCell(new Paragraph(englishE));
            PdfPCell en5 = new PdfPCell(new Paragraph(english_total));
            PdfPCell en6 = new PdfPCell(new Paragraph(""));
            PdfPCell en7 = new PdfPCell(new Paragraph(""));
            PdfPCell en8 = new PdfPCell(new Paragraph(""));

            PdfPCell s1 = new PdfPCell(new Paragraph("LITERATURE"));
            PdfPCell s2 = new PdfPCell(new Paragraph(lit1));
            PdfPCell s3 = new PdfPCell(new Paragraph(lit2));
            PdfPCell s4 = new PdfPCell(new Paragraph(litE));
            PdfPCell s5 = new PdfPCell(new Paragraph(lit_total));
            PdfPCell s6 = new PdfPCell(new Paragraph(""));
            PdfPCell s7 = new PdfPCell(new Paragraph(""));
            PdfPCell s8 = new PdfPCell(new Paragraph(""));

            PdfPCell e1 = new PdfPCell(new Paragraph("MATHEMATICS"));
            PdfPCell e2 = new PdfPCell(new Paragraph(maths1));
            PdfPCell e3 = new PdfPCell(new Paragraph(maths2));
            PdfPCell e4 = new PdfPCell(new Paragraph(mathsE));
            PdfPCell e5 = new PdfPCell(new Paragraph(maths_total));
            PdfPCell e6 = new PdfPCell(new Paragraph(""));
            PdfPCell e7 = new PdfPCell(new Paragraph(""));
            PdfPCell e8 = new PdfPCell(new Paragraph(""));

            PdfPCell sh1 = new PdfPCell(new Paragraph("COMPUTER"));
            PdfPCell sh2 = new PdfPCell(new Paragraph(ict1));
            PdfPCell sh3 = new PdfPCell(new Paragraph(ict2));
            PdfPCell sh4 = new PdfPCell(new Paragraph(ictE));
            PdfPCell sh5 = new PdfPCell(new Paragraph(ict_total));
            PdfPCell sh6 = new PdfPCell(new Paragraph(""));
            PdfPCell sh7 = new PdfPCell(new Paragraph(""));
            PdfPCell sh8 = new PdfPCell(new Paragraph(""));

            PdfPCell bat1 = new PdfPCell(new Paragraph("FRENCH"));
            PdfPCell bat2 = new PdfPCell(new Paragraph(fre1));
            PdfPCell bat3 = new PdfPCell(new Paragraph(fre2));
            PdfPCell bat4 = new PdfPCell(new Paragraph(freE));
            PdfPCell bat5 = new PdfPCell(new Paragraph(fre_total));
            PdfPCell bat6 = new PdfPCell(new Paragraph(""));
            PdfPCell bat7 = new PdfPCell(new Paragraph(""));
            PdfPCell bat8 = new PdfPCell(new Paragraph(""));

            PdfPCell ph1 = new PdfPCell(new Paragraph("CHEMISTRY"));
            PdfPCell ph2 = new PdfPCell(new Paragraph(chem1));
            PdfPCell ph3 = new PdfPCell(new Paragraph(chem2));
            PdfPCell ph4 = new PdfPCell(new Paragraph(chemE));
            PdfPCell ph5 = new PdfPCell(new Paragraph(chem_total));
            PdfPCell ph6 = new PdfPCell(new Paragraph(""));
            PdfPCell ph7 = new PdfPCell(new Paragraph(""));
            PdfPCell ph8 = new PdfPCell(new Paragraph(""));

            PdfPCell ic1 = new PdfPCell(new Paragraph("PHYSICS"));
            PdfPCell ic2 = new PdfPCell(new Paragraph(phy1));
            PdfPCell ic3 = new PdfPCell(new Paragraph(phy2));
            PdfPCell ic4 = new PdfPCell(new Paragraph(phyE));
            PdfPCell ic5 = new PdfPCell(new Paragraph(phy_total));
            PdfPCell ic6 = new PdfPCell(new Paragraph(""));
            PdfPCell ic7 = new PdfPCell(new Paragraph(""));
            PdfPCell ic8 = new PdfPCell(new Paragraph(""));
//
            PdfPCell hh1 = new PdfPCell(new Paragraph("GEOGRAPHY"));
            PdfPCell hh2 = new PdfPCell(new Paragraph(geo1));
            PdfPCell hh3 = new PdfPCell(new Paragraph(geo2));
            PdfPCell hh4 = new PdfPCell(new Paragraph(geoE));
            PdfPCell hh5 = new PdfPCell(new Paragraph(geo_total));
            PdfPCell hh6 = new PdfPCell(new Paragraph(""));
            PdfPCell hh7 = new PdfPCell(new Paragraph(""));
            PdfPCell hh8 = new PdfPCell(new Paragraph(""));

            PdfPCell so1 = new PdfPCell(new Paragraph("BIOLOGY"));
            PdfPCell so2 = new PdfPCell(new Paragraph(bio1));
            PdfPCell so3 = new PdfPCell(new Paragraph(bio2));
            PdfPCell so4 = new PdfPCell(new Paragraph(bioE));
            PdfPCell so5 = new PdfPCell(new Paragraph(bio_total));
            PdfPCell so6 = new PdfPCell(new Paragraph(""));
            PdfPCell so7 = new PdfPCell(new Paragraph(""));
            PdfPCell so8 = new PdfPCell(new Paragraph(""));

            PdfPCell ci1 = new PdfPCell(new Paragraph("CHRISTIAN RELIGIOUS STUDIES"));
            PdfPCell ci2 = new PdfPCell(new Paragraph(crs1));
            PdfPCell ci3 = new PdfPCell(new Paragraph(crs2));
            PdfPCell ci4 = new PdfPCell(new Paragraph(crsE));
            PdfPCell ci5 = new PdfPCell(new Paragraph(crs_total));
            PdfPCell ci6 = new PdfPCell(new Paragraph(""));
            PdfPCell ci7 = new PdfPCell(new Paragraph(""));
            PdfPCell ci8 = new PdfPCell(new Paragraph(""));

            PdfPCell co1 = new PdfPCell(new Paragraph("GOVERNMENT"));
            PdfPCell co2 = new PdfPCell(new Paragraph(gov1));
            PdfPCell co3 = new PdfPCell(new Paragraph(gov2));
            PdfPCell co4 = new PdfPCell(new Paragraph(govE));
            PdfPCell co5 = new PdfPCell(new Paragraph(gov_total));
            PdfPCell co6 = new PdfPCell(new Paragraph(""));
            PdfPCell co7 = new PdfPCell(new Paragraph(""));
            PdfPCell co8 = new PdfPCell(new Paragraph(""));

            PdfPCell ca1 = new PdfPCell(new Paragraph("AGRICULTURAL SCIENCE"));
            PdfPCell ca2 = new PdfPCell(new Paragraph(agric1));
            PdfPCell ca3 = new PdfPCell(new Paragraph(agric2));
            PdfPCell ca4 = new PdfPCell(new Paragraph(agricE));
            PdfPCell ca5 = new PdfPCell(new Paragraph(agric_total));
            PdfPCell ca6 = new PdfPCell(new Paragraph(""));
            PdfPCell ca7 = new PdfPCell(new Paragraph(""));
            PdfPCell ca8 = new PdfPCell(new Paragraph(""));

            PdfPCell ag1 = new PdfPCell(new Paragraph("COMMERCE"));
            PdfPCell ag2 = new PdfPCell(new Paragraph(comm1));
            PdfPCell ag3 = new PdfPCell(new Paragraph(comm2));
            PdfPCell ag4 = new PdfPCell(new Paragraph(commE));
            PdfPCell ag5 = new PdfPCell(new Paragraph(comm_total));
            PdfPCell ag6 = new PdfPCell(new Paragraph(""));
            PdfPCell ag7 = new PdfPCell(new Paragraph(""));
            PdfPCell ag8 = new PdfPCell(new Paragraph(""));

            PdfPCell wr1 = new PdfPCell(new Paragraph("ECONOMICS"));
            PdfPCell wr2 = new PdfPCell(new Paragraph(econ1));
            PdfPCell wr3 = new PdfPCell(new Paragraph(econ2));
            PdfPCell wr4 = new PdfPCell(new Paragraph(econE));
            PdfPCell wr5 = new PdfPCell(new Paragraph(econ_total));
            PdfPCell wr6 = new PdfPCell(new Paragraph(""));
            PdfPCell wr7 = new PdfPCell(new Paragraph(""));
            PdfPCell wr8 = new PdfPCell(new Paragraph(""));

            PdfPCell nr1 = new PdfPCell(new Paragraph("FINE ARTS"));
            PdfPCell nr2 = new PdfPCell(new Paragraph(art1));
            PdfPCell nr3 = new PdfPCell(new Paragraph(art2));
            PdfPCell nr4 = new PdfPCell(new Paragraph(artE));
            PdfPCell nr5 = new PdfPCell(new Paragraph(arts_total));
            PdfPCell nr6 = new PdfPCell(new Paragraph(""));
            PdfPCell nr7 = new PdfPCell(new Paragraph(""));
            PdfPCell nr8 = new PdfPCell(new Paragraph(""));

            PdfPCell v1 = new PdfPCell(new Paragraph("ACCOUNTING"));
            PdfPCell v2 = new PdfPCell(new Paragraph(acc1));
            PdfPCell v3 = new PdfPCell(new Paragraph(acc2));
            PdfPCell v4 = new PdfPCell(new Paragraph(accE));
            PdfPCell v5 = new PdfPCell(new Paragraph(acc_total));
            PdfPCell v6 = new PdfPCell(new Paragraph(""));
            PdfPCell v7 = new PdfPCell(new Paragraph(""));
            PdfPCell v8 = new PdfPCell(new Paragraph(""));

            PdfPCell t1 = new PdfPCell(new Paragraph("TOTAL\t\t\t\t" + score_total));
            PdfPCell t2 = new PdfPCell(new Paragraph(""));
            PdfPCell t3 = new PdfPCell(new Paragraph(""));
            PdfPCell t4 = new PdfPCell(new Paragraph(""));
            PdfPCell t5 = new PdfPCell(new Paragraph(""));
            PdfPCell t6 = new PdfPCell(new Paragraph(""));
            PdfPCell t7 = new PdfPCell(new Paragraph(""));
            PdfPCell t8 = new PdfPCell(new Paragraph(""));

            //Adding cells to the table.
            table.addCell(c1);
            table.addCell(c2);
            table.addCell(c3);
            table.addCell(c4);
            table.addCell(c5);
            table.addCell(c6);
            table.addCell(c7);
            table.addCell(c8);

            table.addCell(en1);
            table.addCell(en2);
            table.addCell(en3);
            table.addCell(en4);
            table.addCell(en5);
            table.addCell(en6);
            table.addCell(en7);
            table.addCell(en8);

            table.addCell(s1);
            table.addCell(s2);
            table.addCell(s3);
            table.addCell(s4);
            table.addCell(s5);
            table.addCell(s6);
            table.addCell(s7);
            table.addCell(s8);

            table.addCell(e1);
            table.addCell(e2);
            table.addCell(e3);
            table.addCell(e4);
            table.addCell(e5);
            table.addCell(e6);
            table.addCell(e7);
            table.addCell(e8);

            table.addCell(sh1);
            table.addCell(sh2);
            table.addCell(sh3);
            table.addCell(sh4);
            table.addCell(sh5);
            table.addCell(sh6);
            table.addCell(sh7);
            table.addCell(sh8);

            table.addCell(bat1);
            table.addCell(bat2);
            table.addCell(bat3);
            table.addCell(bat4);
            table.addCell(bat5);
            table.addCell(bat6);
            table.addCell(bat7);
            table.addCell(bat8);

            table.addCell(ph1);
            table.addCell(ph2);
            table.addCell(ph3);
            table.addCell(ph4);
            table.addCell(ph5);
            table.addCell(ph6);
            table.addCell(ph7);
            table.addCell(ph8);

            table.addCell(ic1);
            table.addCell(ic2);
            table.addCell(ic3);
            table.addCell(ic4);
            table.addCell(ic5);
            table.addCell(ic6);
            table.addCell(ic7);
            table.addCell(ic8);

            table.addCell(hh1);
            table.addCell(hh2);
            table.addCell(hh3);
            table.addCell(hh4);
            table.addCell(hh5);
            table.addCell(hh6);
            table.addCell(hh7);
            table.addCell(hh8);
//
            table.addCell(so1);
            table.addCell(so2);
            table.addCell(so3);
            table.addCell(so4);
            table.addCell(so5);
            table.addCell(so6);
            table.addCell(so7);
            table.addCell(so8);

            table.addCell(ci1);
            table.addCell(ci2);
            table.addCell(ci3);
            table.addCell(ci4);
            table.addCell(ci5);
            table.addCell(ci6);
            table.addCell(ci7);
            table.addCell(ci8);

            table.addCell(co1);
            table.addCell(co2);
            table.addCell(co3);
            table.addCell(co4);
            table.addCell(co5);
            table.addCell(co6);
            table.addCell(co7);
            table.addCell(co8);

            table.addCell(ca1);
            table.addCell(ca2);
            table.addCell(ca3);
            table.addCell(ca4);
            table.addCell(ca5);
            table.addCell(ca6);
            table.addCell(ca7);
            table.addCell(ca8);

            table.addCell(ag1);
            table.addCell(ag2);
            table.addCell(ag3);
            table.addCell(ag4);
            table.addCell(ag5);
            table.addCell(ag6);
            table.addCell(ag7);
            table.addCell(ag8);

            table.addCell(wr1);
            table.addCell(wr2);
            table.addCell(wr3);
            table.addCell(wr4);
            table.addCell(wr5);
            table.addCell(wr6);
            table.addCell(wr7);
            table.addCell(wr8);

            table.addCell(nr1);
            table.addCell(nr2);
            table.addCell(nr3);
            table.addCell(nr4);
            table.addCell(nr5);
            table.addCell(nr6);
            table.addCell(nr7);
            table.addCell(nr8);

            table.addCell(v1);
            table.addCell(v2);
            table.addCell(v3);
            table.addCell(v4);
            table.addCell(v5);
            table.addCell(v6);
            table.addCell(v7);
            table.addCell(v8);

            table.addCell(t1);
            table.addCell(t2);
            table.addCell(t3);
            table.addCell(t4);
            table.addCell(t5);
            table.addCell(t6);
            table.addCell(t7);
            table.addCell(t8);

            document.add(table);
            JOptionPane.showMessageDialog(this, "Result saved");
            document.close();
            pdfWriter.close();

        } catch (DocumentException | FileNotFoundException e) {
            System.out.println(e);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAccounting;
    private javax.swing.JTextField txtAgric;
    private javax.swing.JTextField txtArts;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtBiology;
    private javax.swing.JTextField txtCRS;
    private javax.swing.JTextField txtChemistry;
    private javax.swing.JTextField txtCivic;
    private javax.swing.JTextField txtCommerce;
    private javax.swing.JTextField txtComputer;
    private javax.swing.JTextField txtEcons;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtFMaths;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFrench;
    private javax.swing.JTextField txtGeography;
    private javax.swing.JTextField txtGovernment;
    private javax.swing.JTextField txtLit;
    private javax.swing.JTextField txtMaths;
    private javax.swing.JTextField txtPhysics;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtTotalScore;
    private javax.swing.JTextArea txtTranscript;
    // End of variables declaration//GEN-END:variables
}
