/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import static java.text.DateFormat.getDateInstance;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author FabulousTHO
 */
public class Form extends javax.swing.JFrame {

String conStr = "jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=SchoolManagementSystem;user=sa;password=123456789";
        
static {
    AddSubject addd = new AddSubject();
        AddSubject.txtName.setVisible(true);
        AddSubject.txtteacher0.setVisible(true);
        AddSubject.txtperiod.setVisible(true);
        AddSubject.txttime.setVisible(true);
        AddSubject.txtname1.setVisible(true);
        AddSubject.txtteacher1.setVisible(true);
        AddSubject.txtperiod1.setVisible(true);
        AddSubject.txttime1.setVisible(true);
        AddSubject.txtname2.setVisible(true);
        AddSubject.txtteacher2.setVisible(true);
        AddSubject.txtperiod2.setVisible(true);
        AddSubject.txttime2.setVisible(true);
        AddSubject.txtname3.setVisible(true);
        AddSubject.txtteacher3.setVisible(true);
        AddSubject.txtperiod3.setVisible(true);
        AddSubject.txttime3.setVisible(true);
        AddSubject.txtname4.setVisible(true);
        AddSubject.txtteacher4.setVisible(true);
        AddSubject.txtperiod4.setVisible(true);
        AddSubject.txttime4.setVisible(true);
        

}
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();{

    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btncheckresult = new javax.swing.JButton();
        btntimetable = new javax.swing.JButton();
        btnaddsubject = new javax.swing.JButton();
        LayeredPane = new javax.swing.JLayeredPane();
        PanelFrontPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelTimeTable = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PanelSubject = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtteacherq = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtperiod = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtsubject = new javax.swing.JTextField();
        txttimet1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1261, 520));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        btncheckresult.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btncheckresult.setText("Check Result");
        btncheckresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckresultActionPerformed(evt);
            }
        });
        jPanel4.add(btncheckresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        btntimetable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btntimetable.setText("Time Table");
        btntimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimetableActionPerformed(evt);
            }
        });
        jPanel4.add(btntimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, -1));

        btnaddsubject.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnaddsubject.setText("Add Subject");
        btnaddsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddsubjectActionPerformed(evt);
            }
        });
        jPanel4.add(btnaddsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 520));

        LayeredPane.setLayout(new java.awt.CardLayout());

        PanelFrontPage.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME  TO  EXCEL  INTERNATIONAL  SCHOOL");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/Excel1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TO       BE     GREAT     IS    OUR    PRIORITY");

        javax.swing.GroupLayout PanelFrontPageLayout = new javax.swing.GroupLayout(PanelFrontPage);
        PanelFrontPage.setLayout(PanelFrontPageLayout);
        PanelFrontPageLayout.setHorizontalGroup(
            PanelFrontPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFrontPageLayout.createSequentialGroup()
                .addGroup(PanelFrontPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFrontPageLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1))
                    .addGroup(PanelFrontPageLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel2))
                    .addGroup(PanelFrontPageLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel3)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        PanelFrontPageLayout.setVerticalGroup(
            PanelFrontPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFrontPageLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        LayeredPane.add(PanelFrontPage, "card2");

        PanelTimeTable.setBackground(new java.awt.Color(51, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 4));

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Calendar_27_75px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time Table");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Monday", "English Language", "9:00-10:30", "Biology", "10:30-11:30", "Mathematics", "11:30-12:30", "Accounting", "12:30-1:30"},
                {"Tuesday", "Physics", "9:00-10:30", "Commerce", "10:30-11:30", "English Language", "11:30-12:30", "chemistry", "12:30-1:30"},
                {"Wednesday", "Accounting", "9:00-10:30", "mathematics", "10:30-11:30", "English Language", "11:30-12:30", "Government", "12:30-1:30"},
                {"Thursday", "Mathematics", "9:00-10:30", "Chemistry", "10:30-11:30", "Geography", "11:30-12:30", "Commerce", "12:30-1:30"},
                {"Friday", "Biology", "9:00-10:30", "Mathematics", "10:30-11:30", "Government", "11:30-12:30", "Accounting", "12:30-1:30"}
            },
            new String [] {
                "Days of Week", "Subject", "Time", "Subject", "Time", "Subject", "Time", "Subject", "Time"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout PanelTimeTableLayout = new javax.swing.GroupLayout(PanelTimeTable);
        PanelTimeTable.setLayout(PanelTimeTableLayout);
        PanelTimeTableLayout.setHorizontalGroup(
            PanelTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTimeTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTimeTableLayout.setVerticalGroup(
            PanelTimeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTimeTableLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        LayeredPane.add(PanelTimeTable, "card3");

        PanelSubject.setBackground(new java.awt.Color(0, 153, 153));
        PanelSubject.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 4));
        jPanel5.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Subject  Teacher *");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(410, 120, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Subject");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(20, 30, 80, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Add  Subject");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(100, 70, 130, 20);

        txtteacherq.setBackground(new java.awt.Color(240, 240, 240));
        txtteacherq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtteacherq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteacherqActionPerformed(evt);
            }
        });
        jPanel5.add(txtteacherq);
        txtteacherq.setBounds(540, 120, 250, 20);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(540, 140, 250, 10);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Subject  Name *");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(10, 120, 120, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(100, 90, 120, 10);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.add(jSeparator3);
        jSeparator3.setBounds(20, 50, 70, 10);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.add(jSeparator4);
        jSeparator4.setBounds(140, 140, 250, 10);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.add(jSeparator5);
        jSeparator5.setBounds(540, 190, 250, 10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Subject  Period *");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(410, 170, 120, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Subject  Time *");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 180, 120, 30);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdd);
        btnAdd.setBounds(720, 240, 70, 30);

        txtperiod.setBackground(new java.awt.Color(240, 240, 240));
        txtperiod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtperiod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperiodActionPerformed(evt);
            }
        });
        jPanel5.add(txtperiod);
        txtperiod.setBounds(540, 170, 250, 20);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.add(jSeparator7);
        jSeparator7.setBounds(140, 200, 250, 10);

        txtsubject.setBackground(new java.awt.Color(240, 240, 240));
        txtsubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubjectActionPerformed(evt);
            }
        });
        jPanel5.add(txtsubject);
        txtsubject.setBounds(140, 120, 250, 20);

        txttimet1.setBackground(new java.awt.Color(240, 240, 240));
        txttimet1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttimet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimet1ActionPerformed(evt);
            }
        });
        jPanel5.add(txttimet1);
        txttimet1.setBounds(140, 180, 250, 20);

        PanelSubject.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 980, 310));

        LayeredPane.add(PanelSubject, "card4");

        getContentPane().add(LayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 1100, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       private JFrame frame;
    private void btnaddsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddsubjectActionPerformed
        changePanel(PanelSubject);
        PanelSubject.show();
        setVisible(true);
    }//GEN-LAST:event_btnaddsubjectActionPerformed

    private void btntimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimetableActionPerformed
        changePanel(PanelTimeTable);
        //LayeredPane.removeAll();
        PanelTimeTable.show();
        setVisible(true);

    }//GEN-LAST:event_btntimetableActionPerformed

    private void btncheckresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckresultActionPerformed
           new StudentResult_SSS().show();
           setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btncheckresultActionPerformed

    private void txtteacherqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteacherqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteacherqActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddSubject add  = new AddSubject();
        AddSubject.txtName.setText(this.txtsubject.getText());
        AddSubject.txtteacher0.setText(this.txtteacherq.getText());
        AddSubject.txttime.setText(this.txttimet1.getText());
        AddSubject.txtperiod.setText(this.txtperiod.getText());
        AddSubject ad  = new AddSubject();
        AddSubject.txtname1.setText(this.txtsubject.getText());
        AddSubject.txtteacher1.setText(this.txtteacherq.getText());
        AddSubject.txtperiod1.setText(this.txtperiod.getText());
        AddSubject.txttime1.setText(this.txttimet1.getText());
        AddSubject dd  = new AddSubject();
        AddSubject.txtname2.setText(this.txtsubject.getText());
        AddSubject.txtteacher2.setText(this.txtteacherq.getText());
        AddSubject.txtperiod2.setText(this.txtperiod.getText());
        AddSubject.txttime2.setText(this.txttimet1.getText());
        AddSubject da  = new AddSubject();
        AddSubject.txtname3.setText(this.txtsubject.getText());
        AddSubject.txtteacher3.setText(this.txtteacherq.getText());
        AddSubject.txtperiod3.setText(this.txtperiod.getText());
        AddSubject.txttime3.setText(this.txttimet1.getText());
        AddSubject d  = new AddSubject();
        AddSubject.txtname4.setText(this.txtsubject.getText());
        AddSubject.txtteacher4.setText(this.txtteacherq.getText());
        AddSubject.txtperiod4.setText(this.txtperiod.getText());
        AddSubject.txttime4.setText(this.txttimet1.getText());
        add.setVisible(false);
        add.show();
        ad.setVisible(false);
        //ad.show();
        dd.setVisible(false);
        //dd.show();
        da.setVisible(false);
        //da.show();
        d.setVisible(false);
        //d.show();
        this.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtperiodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperiodActionPerformed
        // TODO add your handling code here:
        //DateFormat df = DateFormat.getDateInstance(DateFormat.LONG,
            // new Locale("nig", "NIG")); 
        //String date = df.format(new Date());
        //System.out.println(date);
    }//GEN-LAST:event_txtperiodActionPerformed

    private void txtsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubjectActionPerformed

    private void txttimet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimet1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Home().show();
        setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Form().setVisible(true);
            }
        });
    }
     public void changePanel(JPanel panel)
            
    {
        LayeredPane.removeAll();
        LayeredPane.add(panel);
        LayeredPane.repaint();
        LayeredPane.revalidate();
        }
//     public void changePanel2(JPanel panel1)
//            
//    {
//        LayeredPane1.removeAll();
//        LayeredPane1.add(panel1);
//        LayeredPane1.repaint();
//        LayeredPane1.revalidate();
//        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayeredPane;
    private javax.swing.JPanel PanelFrontPage;
    private javax.swing.JPanel PanelSubject;
    private javax.swing.JPanel PanelTimeTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnaddsubject;
    private javax.swing.JButton btncheckresult;
    private javax.swing.JButton btntimetable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    javax.swing.JTextField txtperiod;
    private javax.swing.JTextField txtsubject;
    private javax.swing.JTextField txtteacherq;
    javax.swing.JTextField txttimet1;
    // End of variables declaration//GEN-END:variables
}
