/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import schoolmgtsystem.dbhelper.DBHandler;

/**
 *
 * @author Thomas
 */
public class InsertFirstTest extends javax.swing.JFrame {

    /**
     * Creates new form InsertFirstTest
     */
    public InsertFirstTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstMaths = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFirstEnglish = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFirstComm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFirstEcons = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFirstPhy = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFirstBio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFirstAccount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFirstCivic = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFirstFMaths = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFirstLit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFirstGeo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFirstCRS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFirstGov = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFirstChem = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnInsertFirstTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(860, 516));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FIRST TEST");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel1)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 80));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Mathematics");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 30));

        txtFirstMaths.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 100, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("English L.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        txtFirstEnglish.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Commerce");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        txtFirstComm.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Economics");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 30));

        txtFirstEcons.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstEcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 100, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Physics");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, 30));

        txtFirstPhy.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstPhy, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("Biology");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 100, 30));

        txtFirstBio.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstBio, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 100, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("Accounting");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 100, 30));

        txtFirstAccount.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 100, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setText("Civic Edu.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 100, 30));

        txtFirstCivic.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstCivic, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 100, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setText("F. Maths");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, 30));

        txtFirstFMaths.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstFMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 100, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel11.setText("Literature");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 100, 30));

        txtFirstLit.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstLit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 100, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setText("Geography");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 100, 30));

        txtFirstGeo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 100, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel13.setText("C.R.S");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 30));

        txtFirstCRS.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstCRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 100, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel14.setText("Government");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 100, 30));

        txtFirstGov.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstGov, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 100, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel15.setText("Chemistry");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 30));

        txtFirstChem.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(txtFirstChem, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 100, 30));

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCEL");
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 120, 40));

        btnInsertFirstTest.setBackground(new java.awt.Color(0, 153, 204));
        btnInsertFirstTest.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnInsertFirstTest.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertFirstTest.setText("INSERT");
        btnInsertFirstTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertFirstTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertFirstTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertFirstTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertFirstTestActionPerformed
        
        String str = "INSERT INTO sss_one(Maths_Test1, English_Test1, Commerce_Test1,"
                + " Economics_Test1, Physics_Test1, Biology_Test1, Accounting_Test1, "
                + "Civic_Test1, FMaths_Test1, Literature_Test1, Geography_Test1, CRS_Test1,"
                + "Government_Test1, Chemistry_Test1)" 
                + " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        DBHandler handler = new DBHandler();
        
        try {
            PreparedStatement pst = handler.getdbConnection().prepareStatement(str);
            pst.setString(1, txtFirstMaths.getText());
            pst.setString(2, txtFirstEnglish.getText());
            pst.setString(3, txtFirstComm.getText());
            pst.setString(4, txtFirstEcons.getText());
            pst.setString(5, txtFirstPhy.getText());
            pst.setString(6, txtFirstBio.getText());
            pst.setString(7, txtFirstAccount.getText());
            pst.setString(8, txtFirstCivic.getText());
            pst.setString(9, txtFirstFMaths.getText());
            pst.setString(10, txtFirstLit.getText());
            pst.setString(11, txtFirstGeo.getText());
            pst.setString(12, txtFirstCRS.getText());
            pst.setString(13, txtFirstGov.getText());
            pst.setString(14, txtFirstChem.getText());
            pst.executeUpdate();
            
            System.out.println("Inserted");
            pst.close();
            
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DBHandler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnInsertFirstTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertFirstTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertFirstTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertFirstTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertFirstTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertFirstTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsertFirstTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFirstAccount;
    private javax.swing.JTextField txtFirstBio;
    private javax.swing.JTextField txtFirstCRS;
    private javax.swing.JTextField txtFirstChem;
    private javax.swing.JTextField txtFirstCivic;
    private javax.swing.JTextField txtFirstComm;
    private javax.swing.JTextField txtFirstEcons;
    private javax.swing.JTextField txtFirstEnglish;
    private javax.swing.JTextField txtFirstFMaths;
    private javax.swing.JTextField txtFirstGeo;
    private javax.swing.JTextField txtFirstGov;
    private javax.swing.JTextField txtFirstLit;
    private javax.swing.JTextField txtFirstMaths;
    private javax.swing.JTextField txtFirstPhy;
    // End of variables declaration//GEN-END:variables
}
