/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import schoolmgtsystem.model.dbhelper.DBHandler;
import schoolmgtsystem.controller.UserResult;

/**
 *
 * @author FabulousTHO
 */
public class ResultSSS extends javax.swing.JFrame {

    DBHandler handler;
    UserResult userResult;
//    String conStr = "jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=SchoolManagementSystem;user=sa;password=123456789";

    /**
     * Creates new form Multiple
     */
    public ResultSSS() {
        initComponents();
    }

    //OverLoading Constructor
    public ResultSSS(String getID) {
        initComponents();
        ShowStudentID.txtSID.setText(getID);
        txtStudentID.setText(getID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTranscript = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRanking = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtTotalScore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGovernment = new javax.swing.JTextField();
        txtChemistry = new javax.swing.JTextField();
        txtCommerce = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAccounting = new javax.swing.JTextField();
        txtEnglish = new javax.swing.JTextField();
        txtMaths = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBiology = new javax.swing.JTextField();
        txtGeography = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPhysics = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtArts = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtComputer = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFMaths = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtLit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtAgric = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCRS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtFrench = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtCivic = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtEcons = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "Result Printout", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        txtTranscript.setEditable(false);
        txtTranscript.setColumns(20);
        txtTranscript.setRows(5);
        jScrollPane1.setViewportView(txtTranscript);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 380, 490));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Full Name", "Maths", "English", "Accounting", "Commerce", "Chemistry", "Government", "Biology", "Geography", "Physics", "Total Score", "Average", "Ranking"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1260, 100));

        btnRanking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRanking.setText("Ranking");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        jPanel4.add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        btnTranscript.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });
        jPanel4.add(btnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        btnRecord.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRecord.setText("Add Record");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });
        jPanel4.add(btnRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 130, 30));

        btnGenerate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel4.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, -1, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 610, -1, -1));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 610, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Left_30px_1.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "SENIOR SCHOOL RESULT RECORDS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 51, 107, -1));

        txtStudentID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtStudentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 48, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Full Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 107, -1));

        txtFullName.setBackground(new java.awt.Color(255, 255, 255));
        txtFullName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 310, -1));

        txtTotalScore.setEditable(false);
        txtTotalScore.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotalScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalScoreActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total Score");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 107, -1));

        txtAverage.setEditable(false);
        txtAverage.setBackground(new java.awt.Color(255, 255, 255));
        txtAverage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAverage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Average");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 107, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Chemistry");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 107, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Government");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        txtGovernment.setEditable(false);
        txtGovernment.setBackground(new java.awt.Color(255, 255, 255));
        txtGovernment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGovernment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtGovernment, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 90, -1));

        txtChemistry.setEditable(false);
        txtChemistry.setBackground(new java.awt.Color(255, 255, 255));
        txtChemistry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtChemistry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtChemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 90, -1));

        txtCommerce.setEditable(false);
        txtCommerce.setBackground(new java.awt.Color(255, 255, 255));
        txtCommerce.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCommerce.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCommerce, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Commerce");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 107, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Accounting");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 107, -1));

        txtAccounting.setEditable(false);
        txtAccounting.setBackground(new java.awt.Color(255, 255, 255));
        txtAccounting.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAccounting.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAccounting, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 90, -1));

        txtEnglish.setEditable(false);
        txtEnglish.setBackground(new java.awt.Color(255, 255, 255));
        txtEnglish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEnglish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 90, -1));

        txtMaths.setEditable(false);
        txtMaths.setBackground(new java.awt.Color(255, 255, 255));
        txtMaths.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMaths.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 90, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Maths");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 66, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("English");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 107, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 350, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Position");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 107, -1));

        txtPosition.setEditable(false);
        txtPosition.setBackground(new java.awt.Color(255, 255, 255));
        txtPosition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Biology");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        txtBiology.setEditable(false);
        txtBiology.setBackground(new java.awt.Color(255, 255, 255));
        txtBiology.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBiology.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBiology, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 90, -1));

        txtGeography.setEditable(false);
        txtGeography.setBackground(new java.awt.Color(255, 255, 255));
        txtGeography.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGeography.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGeography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographyActionPerformed(evt);
            }
        });
        jPanel1.add(txtGeography, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Geography");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        txtPhysics.setEditable(false);
        txtPhysics.setBackground(new java.awt.Color(255, 255, 255));
        txtPhysics.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPhysics.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPhysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 90, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Physics");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        txtArts.setEditable(false);
        txtArts.setBackground(new java.awt.Color(255, 255, 255));
        txtArts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtArts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtArts, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Fine Arts");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Computer");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));

        txtComputer.setEditable(false);
        txtComputer.setBackground(new java.awt.Color(255, 255, 255));
        txtComputer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtComputer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("F. Maths");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, -1));

        txtFMaths.setEditable(false);
        txtFMaths.setBackground(new java.awt.Color(255, 255, 255));
        txtFMaths.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFMaths.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtFMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Literature");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, -1));

        txtLit.setEditable(false);
        txtLit.setBackground(new java.awt.Color(255, 255, 255));
        txtLit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtLit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtLit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 90, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Agriculture");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 110, -1));

        txtAgric.setEditable(false);
        txtAgric.setBackground(new java.awt.Color(255, 255, 255));
        txtAgric.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAgric.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAgric, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 90, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("C R S");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 80, -1));

        txtCRS.setEditable(false);
        txtCRS.setBackground(new java.awt.Color(255, 255, 255));
        txtCRS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCRS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 90, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("French");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 80, -1));

        txtFrench.setEditable(false);
        txtFrench.setBackground(new java.awt.Color(255, 255, 255));
        txtFrench.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFrench.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtFrench, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 90, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Civic Education");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 120, -1));

        txtCivic.setEditable(false);
        txtCivic.setBackground(new java.awt.Color(255, 255, 255));
        txtCivic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCivic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCivic, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 90, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Economics");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, -1));

        txtEcons.setEditable(false);
        txtEcons.setBackground(new java.awt.Color(255, 255, 255));
        txtEcons.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEcons.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Class");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, -1));

        txtClass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtClass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 110, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 810, 490));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        double[] R = new double[20];

        R[0] = Double.parseDouble(txtEnglish.getText());
        R[1] = Double.parseDouble(txtMaths.getText());
        R[2] = Double.parseDouble(txtCommerce.getText());
        R[3] = Double.parseDouble(txtEcons.getText());
        R[4] = Double.parseDouble(txtPhysics.getText());
        R[5] = Double.parseDouble(txtBiology.getText());
        R[6] = Double.parseDouble(txtAccounting.getText());
        R[7] = Double.parseDouble(txtFMaths.getText());
        R[8] = Double.parseDouble(txtLit.getText());
        R[9] = Double.parseDouble(txtGeography.getText());
        R[10] = Double.parseDouble(txtCRS.getText());
        R[11] = Double.parseDouble(txtGovernment.getText());
        R[12] = Double.parseDouble(txtChemistry.getText());
        R[13] = Double.parseDouble(txtAgric.getText());
        R[14] = Double.parseDouble(txtArts.getText());
        R[15] = Double.parseDouble(txtComputer.getText());
//        R[16] = Double.parseDouble(txtFrench.getText());
//        R[17] = Double.parseDouble(txtCivic.getText());

        R[16] = (R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7] + R[8] + R[9] + R[10] + R[11] + R[12] + R[13] + R[14]
                + R[15] /*+ R[16] + R[17]*/) / 16;
        //R[9] = (R[0] + R[1] + R[2] + R[3] + R[5] + R[6] + R[7])/7;
        R[17] = R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7] + R[8] + R[9] + R[10] + R[11] + R[12] + R[13] + R[14]
                + R[15] /*+ R[16] + R[17]*/;

        String Average = String.format("%.0f", R[16]);
        txtAverage.setText(Average);

        String TotalScore = String.format("%.0f", R[17]);
        txtTotalScore.setText(TotalScore);

        if (R[17] >= 700) {
            txtPosition.setText("1st");
        } else if (R[17] >= 600) {
            txtPosition.setText("2nd");
        } else if (R[17] >= 500) {
            txtPosition.setText("3rd");
        } else if (R[17] >= 400) {
            txtPosition.setText("4th");
        } else if (R[17] >= 300) {
            txtPosition.setText("Average");
        } else if (R[17] >= 200) {
            txtPosition.setText("Fail");
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            txtStudentID.getText(),
            txtFullName.getText(),
            //            txtSurname.getText(),
            //            txtCourseCode.getSelectedItem(),
            txtMaths.getText(),
            txtEnglish.getText(),
            txtAccounting.getText(),
            txtCommerce.getText(),
            txtChemistry.getText(),
            txtGovernment.getText(),
            txtBiology.getText(),
            txtGeography.getText(),
            txtPhysics.getText(),
            txtTotalScore.getText(),
            txtAverage.getText(),
            txtPosition.getText()
        });
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
        txtTranscript.append("                              BRIGHT STARS SCHOOL\n                             (Knowledge for Excellence)"
                + "\n                                        Student Result"
                + "\n_____________________________________"
                + "\nStudent ID:\t\t" + txtStudentID.getText()
                + "\n_____________________________________"
                + "\nFirst Name:\t\t" + txtFullName.getText()
                + "\n_____________________________________"
                + "\nMaths:\t\t" + txtMaths.getText()
                + "\n_____________________________________"
                + "\nEnglish:\t\t" + txtEnglish.getText()
                + "\n_____________________________________"
                + "\nAccounting:\t\t" + txtAccounting.getText()
                + "\n_____________________________________"
                + "\nCommerce:\t\t" + txtCommerce.getText()
                + "\n_____________________________________"
                + "\nChemistry:\t\t" + txtChemistry.getText()
                + "\n_____________________________________"
                + "\nGovernment:\t\t" + txtGovernment.getText()
                + "\n_____________________________________"
                + "\nBiology:\t\t" + txtBiology.getText()
                + "\n_____________________________________"
                + "\nGeography:\t\t" + txtGeography.getText()
                + "\n_____________________________________"
                + "\nPhysics:\t\t" + txtPhysics.getText()
                + "\n_____________________________________"
                + "\nTotal Score:\t\t" + txtTotalScore.getText()
                + "\n_____________________________________"
                + "\nAverage:\t\t" + txtAverage.getText()
                + "\n_____________________________________"
                + "\nPosition:\t\t" + txtPosition.getText()
                + "\n_____________________________________"
        );

    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed

        new ResultEntry().show();
        this.dispose();

    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        handler = new DBHandler();
//        String[] fields = {txtMaths.getText(), txtEnglish.getText(), txtLit.getText(), txtCommerce.getText(), txtGeography.getText(),
//            txtPhysics.getText(), txtBiology.getText(), txtCRS.getText(), txtAccounting.getText(), txtFMaths.getText(), txtEcons.getText(),
//            txtAgric.getText(), txtGovernment.getText(), txtChemistry.getText(), txtArts.getText(), txtComputer.getText(),
//            txtStudentID.getText(), txtFullName.getText()};

        try {
            String str = "SELECT * FROM sss WHERE StudentID = ?";
            PreparedStatement pst = handler.getdbConnection().prepareStatement(str);
            pst.setString(1, txtStudentID.getText());
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {

                txtStudentID.setText(rs.getString("StudentID"));
                txtMaths.setText(rs.getString("Maths_Total"));
                txtEnglish.setText(rs.getString("English_Total"));
                txtLit.setText(rs.getString("Literature_Total"));
                txtCommerce.setText(rs.getString("Commerce_Total"));
                txtEcons.setText(rs.getString("Economics_Total"));
                txtPhysics.setText(rs.getString("Physics_Total"));
                txtBiology.setText(rs.getString("Biology_Total"));
                txtCRS.setText(rs.getString("CRS_Total"));
                txtAccounting.setText(rs.getString("Account_Total"));
//                txtCivic.setText(rs.getString("Civic_Total"));
                txtFMaths.setText(rs.getString("FMaths_Total"));
                txtGeography.setText(rs.getString("Geography_Total"));
                txtAgric.setText(rs.getString("Agric_Total"));
                txtGovernment.setText(rs.getString("Government_Total"));
                txtChemistry.setText(rs.getString("Chemistry_Total"));
                txtArts.setText(rs.getString("Arts_Total"));
                txtComputer.setText(rs.getString("Computer_Total"));
//                txtFrench.setText(rs.getString("French_Total"));

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentResult_SSS.class.getName()).log(Level.SEVERE, null, ex);
        }

        String ID = txtStudentID.getText();
        String getName_Class = "SELECT * FROM student_details WHERE StudentID = ?";
        String validate = "SELECT StudentID FROM sss WHERE StudentID = ?";

        try {
            handler = new DBHandler();
            ResultSet rs = null;
            ResultSet rs1 = null;
            PreparedStatement pst = handler.getdbConnection().prepareStatement(getName_Class);
            PreparedStatement pst1 = handler.getdbConnection().prepareStatement(validate);

            pst.setString(1, txtStudentID.getText());
            pst1.setString(1, txtStudentID.getText());

            rs = pst.executeQuery();
            rs1 = pst1.executeQuery();

            if (rs.next() && rs1.next()) {

                getClassID = rs.getString("StudentID");
                getAdmClass = rs.getString("AdmissionClass");
                getSname = rs.getString("StudentName");
                getSchoolID = rs1.getString("StudentID");

                System.out.println(getClassID + ", " + getSchoolID);

                if (getClassID.equals(getSchoolID)) {

                    txtClass.setText(getAdmClass);
                    txtFullName.setText(getSname);

                }

            } else {
                System.out.println("Not Valid");
                JOptionPane.showMessageDialog(this, "No Student ID as " + ID + " in Senior Secondary");
                txtStudentID.setText(getClassID);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        JTextField temp = null;
        for (Component C : jPanel1.getComponents()) {
            if (C.getClass().toString().contains("javax.swing.JTextField")) {

                temp = (JTextField) C;
                temp.setText(null);

                JTextArea tem = null;
                for (Component A : jPanel1.getComponents()) {
                    if (A.getClass().toString().contains("javax.swing.JTextArea")) {

                        tem = (JTextArea) A;
                        tem.setText(null);
                    }
                    txtTranscript.setText("");
                }
            }
        }

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        int sel = JOptionPane.showConfirmDialog(this, "Do you want to print Result?");
        if (sel == 0) {
            try {
                printResult();
            } catch (IOException ex) {
                Logger.getLogger(ResultNursery.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (sel == 1) {
            this.show();
        }
        if (sel == 2) {
            this.show();
        }

    }//GEN-LAST:event_btnPrintActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        new ResultView().show();
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void txtTotalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalScoreActionPerformed

    private void txtGeographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeographyActionPerformed
    private JFrame frame;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultSSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ResultSSS().setVisible(true);
        });
    }

//    public void insertDB() {
//
//        handler = new DBHandler();
//
//        String id = txtStudentID.getText();
////        String email = txtEmail.getText();
//        String firstname = txtFirstName.getText();
//        String surname = txtSurname.getText();
////        int coursecode = txtCourseCode.getSelectedIndex();
//        String maths = txtMaths.getText();
//        String english = txtEnglish.getText();
//        String account = txtAccounting.getText();
//        String commerce = txtCommerce.getText();
//        String chemis = txtChemistry.getText();
//        String gov = txtGovernment.getText();
//        String bio = txtBiology.getText();
//        String geo = txtGeography.getText();
//        String phy = txtPhysics.getText();
//
//        userResult = new UserResult(id, /*email,*/ firstname, surname, /*coursecode,*/ maths, english, account,
//                commerce, chemis, gov, bio, geo, phy);
//
//        handler.insertDB(userResult);
//
////        txtEmail.setText("");
//        txtFirstName.setText("");
//        txtSurname.setText("");
////        txtCourseCode.setSelectedIndex(0);
//        txtMaths.setText("");
//        txtEnglish.setText("");
//        txtAccounting.setText("");
//        txtCommerce.setText("");
//        txtChemistry.setText("");
//        txtGovernment.setText("");
//        txtBiology.setText("");
//        txtGeography.setText("");
//        txtPhysics.setText("");
//
//    }
    public void printResult() throws IOException {

        //PreparedStatement to get the 1st and 2nd Test score
        String str = "select * from sss where StudentID = ?";

        handler = new DBHandler();

        //Variables to reference Test and Exam from the Database
        String english1 = null, english2 = null, englishE = null, maths1 = null, maths2 = null, mathsE = null, crs1 = null,
                crs2 = null, crsE = null, civic1 = null, civic2 = null, civicE = null, ict1 = null, ict2 = null, ictE = null,
                econ1 = null, econ2 = null, econE = null, agric1 = null, agric2 = null, agricE = null, lit1 = null, lit2 = null,
                litE = null, art1 = null, art2 = null, artE = null, comm1 = null, comm2 = null, commE = null, fre1 = null, fre2 = null,
                freE = null, gov1 = null, gov2 = null, govE = null, phy1 = null, phy2 = null, phyE = null, chem1 = null, chem2 = null,
                chemE = null, geo1 = null, geo2 = null, geoE = null, acc1 = null, acc2 = null, accE = null, fmaths1 = null, fmaths2 = null,
                fmathsE = null, bio1 = null, bio2 = null, bioE = null;

        try {
            PreparedStatement pst = handler.getdbConnection().prepareStatement(str);

//             Statement pst = handler.getdbConnection().createStatement();
            pst.setString(1, txtStudentID.getText());

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                txtStudentID.setText(rs.getString("StudentID"));
                english1 = rs.getString("English1");
                english2 = rs.getString("English2");
                englishE = rs.getString("English_Exam");
                maths1 = rs.getString("Maths1");
                maths2 = rs.getString("Maths2");
                mathsE = rs.getString("Maths_Exam");
                crs1 = rs.getString("CRS1");
                crs2 = rs.getString("CRS2");
                crsE = rs.getString("CRS_Exam");
                fmaths1 = rs.getString("FMaths1");
                fmaths2 = rs.getString("FMaths2");
                fmathsE = rs.getString("FMaths_Exam");
                acc1 = rs.getString("Account1");
                acc2 = rs.getString("Account2");
                accE = rs.getString("Account_Exam");
                phy1 = rs.getString("Physics1");
                phy2 = rs.getString("Physics2");
                phyE = rs.getString("Physics_Exam");
                bio1 = rs.getString("Biology1");
                bio2 = rs.getString("Biology2");
                bioE = rs.getString("Biology_Exam");
                civic1 = rs.getString("Civic1");
                civic2 = rs.getString("Civic2");
                civicE = rs.getString("Civic_Exam");
                gov1 = rs.getString("Government1");
                gov2 = rs.getString("Government2");
                govE = rs.getString("Government_Exam");
                ict1 = rs.getString("Computer1");
                ict2 = rs.getString("Computer2");
                ictE = rs.getString("Computer_Exam");
                econ1 = rs.getString("Economics1");
                econ2 = rs.getString("Economics2");
                econE = rs.getString("Economics_Exam");
                agric1 = rs.getString("Agric1");
                agric2 = rs.getString("Agric2");
                agricE = rs.getString("Agric_Exam");
                lit1 = rs.getString("Literature1");
                lit2 = rs.getString("Literature2");
                litE = rs.getString("Literature_Exam");
                geo1 = rs.getString("Geography1");
                geo2 = rs.getString("Geography2");
                geoE = rs.getString("Geography_Exam");
                art1 = rs.getString("Arts1");
                art2 = rs.getString("Arts2");
                artE = rs.getString("Arts_Exam");
                comm1 = rs.getString("Commerce1");
                comm2 = rs.getString("Commerce2");
                commE = rs.getString("Commerce_Exam");
                chem1 = rs.getString("Chemistry1");
                chem2 = rs.getString("Chemistry2");
                chemE = rs.getString("Chemistry_Exam");
                fre1 = rs.getString("French1");
                fre2 = rs.getString("French2");
                freE = rs.getString("French_Exam");

            }

            System.out.println("1st Test " + english1);
            System.out.println("2st Test " + english2);
            System.out.println("Exam " + englishE);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ResultNursery.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Creating a file dialog with file chooser
        //Prints out file in PDF format
        JFileChooser chooser = new JFileChooser();
        chooser.showSaveDialog(this);
        chooser.getSelectedFile();

        File file = chooser.getSelectedFile();

        Document document = new Document();
        Font font = new Font();

        try {

            String english_total = txtEnglish.getText();
            String maths_total = txtMaths.getText();
            String comm_total = txtCommerce.getText();
            String econ_total = txtEcons.getText();
            String phy_total = txtPhysics.getText();
            String bio_total = txtBiology.getText();
            String acc_total = txtAccounting.getText();
            String civic_total = txtCivic.getText();
            String fmaths_total = txtFMaths.getText();
            String lit_total = txtLit.getText();
            String geo_total = txtGeography.getText();
            String crs_total = txtCRS.getText();
            String gov_total = txtGovernment.getText();
            String chem_total = txtChemistry.getText();
            String agric_total = txtAgric.getText();
            String arts_total = txtArts.getText();
            String ict_total = txtComputer.getText();
            String fre_total = txtFrench.getText();
            String score_total = txtTotalScore.getText();
            String average_total = txtAverage.getText();
            String position_total = txtPosition.getText();

            System.out.println("English Total " + english_total);

            PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(file));
            document.open();

            Image image = Image.getInstance("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\SchoolMgtSystem\\Bright_Stars.png");
            image.setAbsolutePosition(70, 738);

            Font infofont = new Font(Font.FontFamily.TIMES_ROMAN, 11.5f, Font.BOLD);
            Font detailsfont = new Font(Font.FontFamily.HELVETICA, 11f, Font.NORMAL);
            Font namefont = new Font(Font.FontFamily.TIMES_ROMAN, 12.5f, Font.BOLD);
            Font motofont = new Font(Font.FontFamily.TIMES_ROMAN, 9, Font.BOLD);

            Paragraph ti = new Paragraph("", namefont);
            ti.add("BRIGHT STARS SENIOR SECONDARY SCHOOL");
            ti.setAlignment(Element.ALIGN_CENTER);
//            font = ti.getFont();
//            font.setSize(12.5f);

            Paragraph sl = new Paragraph("", motofont);
            sl.add("(NURSERY, PRIMARY & SECONDARY)");
            sl.setAlignment(Element.ALIGN_CENTER);
            font = sl.getFont();
            font.setSize(10);
            sl.setSpacingBefore(0f);
            sl.setSpacingAfter(0f);

            Paragraph sti = new Paragraph("", infofont);
            sti.add("Omorodion Osaretin Str, Off Okuwague\nEvbabogun Road, Off Sapele Road, Benin City");
            sti.setAlignment(Element.ALIGN_CENTER);
            sti.setSpacingBefore(0f);
            sti.setSpacingAfter(0f);

            Paragraph tele = new Paragraph("", infofont);
            tele.add("TEL: 07067183000" + " \tEmail: informbrightstars@yahoo.com");
            tele.setAlignment(Element.ALIGN_CENTER);
            tele.setSpacingBefore(0f);
            tele.setSpacingAfter(0f);

            Paragraph mot = new Paragraph("", infofont);
            mot.add("MOTTO: Knowledge for Excellence");
            mot.setAlignment(Element.ALIGN_CENTER);
            mot.setSpacingBefore(0f);
            mot.setSpacingAfter(0f);

            Paragraph name = new Paragraph("", detailsfont);
            name.setAlignment(Element.ALIGN_CENTER);
            name.add("Full Name: " + txtFullName.getText()
                    + "   Class: ________" + "   Term: ________");
            name.setSpacingBefore(7f);
            name.setSpacingAfter(10f);

//            Paragraph img = new Paragraph();
//            img.add(Image.getInstance("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\SchoolMgtSystem\\Bright_Stars.png"));
//            img.setAlignment(Element.ALIGN_CENTER);
            //Adding to the Document
            document.add(image);
            document.add(ti);
            document.add(sl);
            document.add(sti);
            document.add(tele);
            document.add(mot);
            document.add(name);

//            PdfPCell c1 = new PdfPCell(new Paragraph("SUBJECTS"));
//            PdfPCell c2 = new PdfPCell(new Paragraph("1ST\nTEST"));
//            PdfPCell c3 = new PdfPCell(new Paragraph("2ND\nTEST"));
//            PdfPCell c4 = new PdfPCell(new Paragraph("EXAM"));
//            PdfPCell c5 = new PdfPCell(new Paragraph("TOTAL"));
//            PdfPCell c6 = new PdfPCell(new Paragraph("GRADE"));
//            PdfPCell c7 = new PdfPCell(new Paragraph("POSITOIN"));
//            PdfPCell c8 = new PdfPCell(new Paragraph("SIGN"));
//            PdfPCell bat1 = new PdfPCell(new Paragraph("FRENCH"));
//            PdfPCell bat2 = new PdfPCell(new Paragraph(fre1));
//            PdfPCell bat3 = new PdfPCell(new Paragraph(fre2));
//            PdfPCell bat4 = new PdfPCell(new Paragraph(freE));
//            PdfPCell bat5 = new PdfPCell(new Paragraph(fre_total));
//            PdfPCell bat6 = new PdfPCell(new Paragraph(""));
//            PdfPCell bat7 = new PdfPCell(new Paragraph(""));
//            PdfPCell bat8 = new PdfPCell(new Paragraph(""));
//            DEFINING THE TABLE WITH 8 COLUMNS
            PdfPTable table = new PdfPTable(8);
            table.setWidthPercentage(105);
            table.setSpacingBefore(8f);
            table.setSpacingAfter(8f);

//            DEFINING COLUMN WIDTH
            float[] colWidth = {1.7f, 0.3f, 0.3f, 0.3f, 0.4f, 0.5f, 0.5f, 0.4f};
            table.setWidths(colWidth);

//            DEFINING FONT SIZES FOR THE TABLE HEADER ANND TABLE CELLS
            Font headerfont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);
            Font cellfont = new Font(Font.FontFamily.HELVETICA, 10.8f, Font.NORMAL);
            Font cellfonts = new Font(Font.FontFamily.HELVETICA);

//            ADDING CELLS TO THE TABLE
            table.addCell(new PdfPCell(new Phrase("", headerfont)));
            table.addCell(new PdfPCell(new Phrase("  1ST\n TEST", headerfont)));
            table.addCell(new PdfPCell(new Phrase("  2ND\n TEST", headerfont)));
            table.addCell(new PdfPCell(new Phrase("EXAM", headerfont)));
            table.addCell(new PdfPCell(new Phrase("  TOTAL", headerfont)));
            table.addCell(new PdfPCell(new Phrase("   GRADE", headerfont)));
            table.addCell(new PdfPCell(new Phrase(" POSITION", headerfont)));
            table.addCell(new PdfPCell(new Phrase("   SIGN", headerfont)));

            table.addCell(new PdfPCell(new Phrase("ENGLISH LANGUAGE", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + english1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + english2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + englishE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + english_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("LITERATURE", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + lit1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + lit2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + litE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + lit_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("MATHEMATICS", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + maths1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + maths2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + mathsE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + maths_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("COMPUTER", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + ict1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + ict2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + ictE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + ict_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("CHEMISTRY", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + chem1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + chem2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + chemE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + chem_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("PHYSICS", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + phy1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + phy2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + phyE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + phy_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("GEOGRAPHY", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + geo1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + geo2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + geoE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + geo_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("BIOLOGY", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + bio1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + bio2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + bioE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + bio_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("CHRISTIAN RELIGIOUS STUDIES", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + crs1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + crs2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + crsE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + crs_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("GOVEERNMENT", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + gov1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + gov2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + govE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + gov_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("AGRICULTURAL SCIENCE", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + agric1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + agric2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + agricE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + agric_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("COMMERCE", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + comm1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + comm2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + commE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + comm_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("ECONOMICS", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + econ1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + econ2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + econE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + econ_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("FINE ARTS", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + art1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + art2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + artE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + arts_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("ACCOUNTING", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + acc1, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + acc2, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + accE, cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + acc_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            table.addCell(new PdfPCell(new Phrase("TOTAL", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   ", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   ", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   ", cellfont)));
            table.addCell(new PdfPCell(new Phrase("   " + score_total, cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));
            table.addCell(new PdfPCell(new Phrase("", cellfont)));

            document.add(table);

            Paragraph total = new Paragraph(new Phrase("", cellfont));
            total.add("Total score:    " + score_total + "        Out of: _______ " + "       Average score:    " + average_total
                    + "       Position:    " + position_total + "        Out of: _______");

            Paragraph result = new Paragraph(new Phrase("", cellfont));
            result.add("RESULT: PASS/FAIL _____________________________________________________________________");
            result.setSpacingBefore(5f);

            Paragraph form = new Paragraph(new Phrase("", cellfont));
            form.add("Form Master's Report: ____________________________________________________________________");
            form.setSpacingBefore(5f);

            Paragraph behavior = new Paragraph(new Phrase("", cellfont));
            behavior.add("Behaviour: _____________________________________________________________________________");
            behavior.setSpacingBefore(5f);

            Paragraph observe = new Paragraph(new Phrase("", cellfont));
            observe.add("Special Observation: _____________________________________________________________________");
            observe.setSpacingBefore(5f);

            Paragraph sign = new Paragraph(new Phrase("", cellfont));
            sign.add("                                                                                                      ___________________________________");
            sign.setSpacingBefore(5f);

            Paragraph signs = new Paragraph(new Phrase("", cellfont));
            signs.add("                                                                                                              Form Master's Signature and Date");

            Paragraph principal = new Paragraph(new Phrase("", cellfont));
            principal.add("Principal's Report: _______________________________________________________________________");
            principal.setSpacingBefore(5f);

            Paragraph principals = new Paragraph(new Phrase("", cellfont));
            principals.add("______________________________________________________________________________________");
            principals.setSpacingBefore(5f);

            Paragraph next = new Paragraph(new Phrase("", cellfont));
            next.add("Next Term Begins:_______________________________________________________________________");
            next.setSpacingBefore(5.5f);

            Paragraph key = new Paragraph(new Phrase("", cellfont));
            key.add("       KEY                                                                                       Fees Owning: ________________________");
            key.setSpacingBefore(5f);

            Paragraph excel = new Paragraph(new Phrase("", cellfont));
            excel.add("89-100 = A - EXCELLENT                                                         Next Term Fee: ________________________");
            excel.setSpacingBefore(3.5f);

            Paragraph vgood = new Paragraph(new Phrase("", cellfont));
            vgood.add(" 79-72 =  A - V. GOOD                                                                       Total: ____________________________");
            vgood.setSpacingBefore(3.5f);

            Paragraph good = new Paragraph(new Phrase("", cellfont));
            good.add(" 69-62 =  B - GOOD");
            good.setSpacingBefore(3.5f);

            Paragraph pass = new Paragraph(new Phrase("", cellfont));
            pass.add(" 69-62 =  C - PASS");
            pass.setSpacingBefore(3.5f);

            Paragraph fair = new Paragraph(new Phrase("", cellfont));
            fair.add(" 69-62 =  D - FAIR                                                                                ________________________________");
            fair.setSpacingBefore(3.5f);
            fair.setSpacingAfter(0);

            Paragraph fail = new Paragraph(new Phrase("", cellfont));
            fail.add(" 69-62 =  E - FAIL                                                                                        Principal's Signature and Date");

            document.add(total);
            document.add(result);
            document.add(form);
            document.add(behavior);
            document.add(observe);
            document.add(sign);
            document.add(signs);
            document.add(principal);
            document.add(principals);
            document.add(next);
            document.add(key);
            document.add(excel);
            document.add(vgood);
            document.add(good);
            document.add(pass);
            document.add(fair);
            document.add(fail);
            JOptionPane.showMessageDialog(this, "Result saved");
            document.close();
            pdfWriter.close();

        } catch (DocumentException | FileNotFoundException e) {
            System.out.println(e);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAccounting;
    private javax.swing.JTextField txtAgric;
    private javax.swing.JTextField txtArts;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtBiology;
    private javax.swing.JTextField txtCRS;
    private javax.swing.JTextField txtChemistry;
    private javax.swing.JTextField txtCivic;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtCommerce;
    private javax.swing.JTextField txtComputer;
    private javax.swing.JTextField txtEcons;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtFMaths;
    private javax.swing.JTextField txtFrench;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtGeography;
    private javax.swing.JTextField txtGovernment;
    private javax.swing.JTextField txtLit;
    private javax.swing.JTextField txtMaths;
    private javax.swing.JTextField txtPhysics;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtTotalScore;
    private javax.swing.JTextArea txtTranscript;
    // End of variables declaration//GEN-END:variables

    String getClassID;
    String getSchoolID;
    String getAdmClass;
    String getSname;

}
