/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import schoolmgtsystem.dbhelper.DBHandler;

/**
 *
 * @author Thomas
 */
public class StudentMgt extends javax.swing.JFrame {

    String s;
    BufferedImage bufferedImage;
    ImageIcon imageIcon;
    InputStream input;
    DBHandler handler = new DBHandler();

    /**
     * Creates new form ManageStudent
     */
    public StudentMgt() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        CYes = new javax.swing.JCheckBox();
        CNo = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        Medical = new javax.swing.JComboBox<>();
        DisabilityType = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        PhysicalDis = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CMale = new javax.swing.JCheckBox();
        CFemale = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        RegDate = new com.toedter.calendar.JDateChooser();
        EndDate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblImage = new javax.swing.JLabel();
        btnPassport = new javax.swing.JButton();
        AdmClass = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        PreSchool = new javax.swing.JTextField();
        PreClass = new javax.swing.JTextField();
        Session = new com.toedter.calendar.JYearChooser();
        txtID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("STUDENT MANAGEMENT(Update)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 26));

        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Xbox_X.png"))); // NOI18N
        btnClose.setToolTipText("close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Details", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Student ID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Full Name");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 250, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 250, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("previous School");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 250, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Previous Class");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, -1));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 250, 10));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Disability ?");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        buttonGroup2.add(CYes);
        CYes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CYes.setText("Yes");
        CYes.setBorderPainted(true);
        jPanel3.add(CYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        buttonGroup2.add(CNo);
        CNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CNo.setSelected(true);
        CNo.setText("No");
        CNo.setBorderPainted(true);
        CNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(CNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Medical Condition");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, -1));

        Medical.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Medical.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Anxiety", "Obesity", "Diabetes", "Back pain", "Allergic rhinitis", "Hypertention", "Reflux esophagitis", "Hyperlipidemia", "Others" }));
        jPanel3.add(Medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 230, 30));

        DisabilityType.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        DisabilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Vision", "Hearing", "Thinking", "Learning", "Movement", "Mental health", "Communicating", "Social relationships", "Others" }));
        jPanel3.add(DisabilityType, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 230, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Disability Type");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 100, -1));

        PhysicalDis.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        PhysicalDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Arthritis", "Back injury", "Amputation", "Spina bifida", "Cerebral palsy", "Multiple sclerosis", "Spinal cord injury", "Muscular dystrophy", "Others" }));
        jPanel3.add(PhysicalDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 230, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Physical Disabilities");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Gender");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        buttonGroup1.add(CMale);
        CMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMale.setSelected(true);
        CMale.setText("Male");
        CMale.setBorderPainted(true);
        jPanel3.add(CMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        buttonGroup1.add(CFemale);
        CFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CFemale.setText("Female");
        CFemale.setBorderPainted(true);
        CFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(CFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Admission Class");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Session");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Registration Date");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        RegDate.setBackground(new java.awt.Color(255, 255, 255));
        RegDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegDate.setForeground(new java.awt.Color(51, 51, 51));
        RegDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel3.add(RegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 140, 30));

        EndDate.setBackground(new java.awt.Color(255, 255, 255));
        EndDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EndDate.setForeground(new java.awt.Color(51, 51, 51));
        EndDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel3.add(EndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 140, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("End Date");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 140, 10));

        lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 220, 200));

        btnPassport.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnPassport.setForeground(new java.awt.Color(0, 102, 204));
        btnPassport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Add.png"))); // NOI18N
        btnPassport.setText("Edit Passport");
        btnPassport.setToolTipText("Edit Passport");
        btnPassport.setBorder(null);
        btnPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassportActionPerformed(evt);
            }
        });
        jPanel3.add(btnPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 130, 36));

        AdmClass.setBackground(new java.awt.Color(255, 255, 255));
        AdmClass.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        AdmClass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AdmClass.setText("Admission Class");
        AdmClass.setBorder(null);
        jPanel3.add(AdmClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 140, 20));

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name.setText("Full Name");
        Name.setBorder(null);
        jPanel3.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 250, 20));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("Password");
        password.setBorder(null);
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 250, 20));

        PreSchool.setBackground(new java.awt.Color(255, 255, 255));
        PreSchool.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        PreSchool.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PreSchool.setText("Previous School");
        PreSchool.setBorder(null);
        jPanel3.add(PreSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 250, 20));

        PreClass.setBackground(new java.awt.Color(255, 255, 255));
        PreClass.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        PreClass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PreClass.setText("Previous Class");
        PreClass.setBorder(null);
        jPanel3.add(PreClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 250, 20));

        Session.setBackground(new java.awt.Color(255, 255, 255));
        Session.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(Session, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 140, 30));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(51, 51, 51));
        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, 30));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 102, 204));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("Sign up");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 80, 40));

        btnRetrieve.setBackground(new java.awt.Color(255, 255, 255));
        btnRetrieve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRetrieve.setForeground(new java.awt.Color(0, 102, 204));
        btnRetrieve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Data_Recovery1.png"))); // NOI18N
        btnRetrieve.setText("Retrieve");
        btnRetrieve.setToolTipText("Retrieve");
        btnRetrieve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });
        jPanel3.add(btnRetrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 100, 40));

        btncancel.setBackground(new java.awt.Color(255, 255, 255));
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(0, 102, 204));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Cancel.png"))); // NOI18N
        btncancel.setText("Cancel");
        btncancel.setToolTipText("Cancel");
        btncancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel3.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 90, 40));

        lblError.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 80, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 910, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked

        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed

        String id = txtID.getText();
        String name = Name.getText();
        String preSchool = PreSchool.getText();
        String preClass = PreClass.getText();
        String admClass = AdmClass.getText();
        int session = Session.getYear();
        Date regDate = RegDate.getDate();
        Date endDate = EndDate.getDate();
        String pass = password.getText();
        String medical = (String) Medical.getSelectedItem();
        String phyDis = (String) PhysicalDis.getSelectedItem();
        String disType = (String) DisabilityType.getSelectedItem();
        String disYes = CYes.getText();
        String disNo = CNo.getText();
        String male = CMale.getText();
        String female = CFemale.getText();

        handler = new DBHandler();
        ResultSet rs = null;
        if (!id.equals("")) {
            String select = "SELECT * FROM student_details WHERE StudentID = ?";
            try {
                PreparedStatement pst = handler.getdbConnection().prepareStatement(select);
                pst.setString(1, id);
                int counter = 0;
                rs = pst.executeQuery();
                if (rs.next()) {
                    counter++;
                    name = rs.getString("StudentName");
                    preSchool = rs.getString("PreviousSchool");
                    preClass = rs.getString("PreviousClass");
                    admClass = rs.getString("AdmissionClass");
                    session = rs.getInt("Session");
                    regDate = rs.getDate("RegDate");
                    endDate = rs.getDate("EndDate");
                    pass = rs.getString("Password");
                    medical = rs.getString("MedicalCondition");
                    phyDis = rs.getString("PhysicalDisability");
                    disType = rs.getString("DisabilityType");
                    bufferedImage = ImageIO.read(rs.getBinaryStream("Passport"));
                    if (disNo.equals(rs.getString("Disability"))) {
                        disNo = "No";
                    } else {
                        disYes = "Yes";
                    }
                    if (male.equals(rs.getString("Gender"))) {
                        male = "Male";
                    } else {
                        female = "Female";
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No Student ID as " + id);
                    JTextField temp = null;
                    for (Component C : jPanel1.getComponents()) {
                        if (C.getClass().toString().contains("javax.swing.JTextField")) {

                            temp = (JTextField) C;
                            temp.setText(null);
                        }
                    }
                    password.setText(null);
                    Name.setText(null);
                    AdmClass.setText(null);
                    PreClass.setText(null);
                    Session.setYear(0);
                    PreSchool.setText(null);
                    RegDate.setDate(null);
                    EndDate.setDate(null);
                    lblImage.setText(null);
                    lblImage.setIcon(null);
                }

                if (counter == 1) {
                    Name.setText(name);
                    PreSchool.setText(preSchool);
                    PreClass.setText(preClass);
                    AdmClass.setText(admClass);
                    Session.setYear(session);
                    RegDate.setDate(regDate);
                    EndDate.setDate(endDate);
                    password.setText(pass);
                    Medical.setSelectedItem(medical);
                    PhysicalDis.setSelectedItem(phyDis);
                    DisabilityType.setSelectedItem(disType);
                    CNo.setText(disNo);
                    CYes.setText(disYes);
                    CMale.setText(male);
                    CFemale.setText(female);

                    imageIcon = new ImageIcon(new ImageIcon(bufferedImage).getImage().getScaledInstance(lblImage.getWidth(),
                            lblImage.getHeight(), Image.SCALE_DEFAULT));
                    lblImage.setIcon(imageIcon);
                    lblError.setText("");

                } else {
                    JOptionPane.showMessageDialog(this, "Can't retrieve data !");
                }

            } catch (ClassNotFoundException | SQLException | IOException ex) {
                Logger.getLogger(StudentMgt.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            lblError.setText("ID is needed !");

            JTextField temp = null;
            for (Component C : jPanel1.getComponents()) {
                if (C.getClass().toString().contains("javax.swing.JTextField")) {
                    temp = (JTextField) C;
                    temp.setText(null);
                }
            }
            password.setText(null);
            Name.setText(null);
            AdmClass.setText(null);
            PreClass.setText(null);
            Session.setYear(0);
            PreSchool.setText(null);
            RegDate.setDate(null);
            EndDate.setDate(null);
            lblImage.setText(null);
            lblImage.setIcon(null);
        }

    }//GEN-LAST:event_btnRetrieveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed

        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        handler = new DBHandler();
        String update = "UPDATE student_details SET StudentName=?,Gender=?,PreviousSchool=?,PreviousClass=?,AdmissionClass=?,"
                + "Session=?,PhysicalDisability=?,DisabilityType=?,MedicalCondition=?,Passport=?,Disability=?,RegDate=?,EndDate=?,Password=?"
                + "WHERE StudentID=?";

        try {
            try (PreparedStatement pst = handler.getdbConnection().prepareStatement(update)) {

                pst.setString(1, Name.getText());

                String gender;
                if (CMale.isSelected()) {
                    gender = "Male";
                } else {
                    gender = "Female";
                }
                pst.setString(2, gender);
                pst.setString(3, PreSchool.getText());
                pst.setString(4, PreClass.getText());
                pst.setString(5, AdmClass.getText());
                pst.setInt(6, Session.getYear());
                pst.setString(7, (String) PhysicalDis.getSelectedItem());
                pst.setString(8, (String) DisabilityType.getSelectedItem());
                pst.setString(9, (String) Medical.getSelectedItem());

                input = new FileInputStream(new File(s));
                pst.setBlob(10, input);

                String disability;
                if (CYes.isSelected()) {
                    disability = "Yes";
                } else {
                    disability = "No";
                }

                pst.setString(11, disability);
                pst.setDate(12, convertUtilDateToSqlDate(RegDate.getDate()));
                pst.setDate(13, convertUtilDateToSqlDate(EndDate.getDate()));
                pst.setString(14, password.getText());
                pst.setString(15, txtID.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Saved");
                pst.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(StudentSignup.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentSignup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassportActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("*.image", "jpg", "gif", "png");
        chooser.addChoosableFileFilter(extensionFilter);
        int result = chooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lblImage.setIcon(resizeImage(path));
            s = path;
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No Data");
        }
    }//GEN-LAST:event_btnPassportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentMgt().setVisible(true);
        });
    }

    //Getting image size
    public ImageIcon resizeImage(String imgPath) {
        ImageIcon myImage = new ImageIcon(imgPath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);

        return image;

    }

    private java.sql.Date convertUtilDateToSqlDate(java.util.Date date) {
        if (date != null) {
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField AdmClass;
    private javax.swing.JCheckBox CFemale;
    private javax.swing.JCheckBox CMale;
    private javax.swing.JCheckBox CNo;
    private javax.swing.JCheckBox CYes;
    public static javax.swing.JComboBox<String> DisabilityType;
    public static com.toedter.calendar.JDateChooser EndDate;
    public static javax.swing.JComboBox<String> Medical;
    public static javax.swing.JTextField Name;
    public static javax.swing.JComboBox<String> PhysicalDis;
    public static javax.swing.JTextField PreClass;
    public static javax.swing.JTextField PreSchool;
    public static com.toedter.calendar.JDateChooser RegDate;
    public static com.toedter.calendar.JYearChooser Session;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnPassport;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btncancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblError;
    public static javax.swing.JLabel lblImage;
    public static javax.swing.JTextField password;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
