/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import schoolmgtsystem.dbhelper.DBHandler;

/**
 *
 * @author Thomas
 */
public class StudentMgt extends javax.swing.JFrame {

    String s;
    BufferedImage bufferedImage;
    ImageIcon imageIcon;
    InputStream input;
    DBHandler handler = new DBHandler();

    /**
     * Creates new form ManageStudent
     */
    public StudentMgt() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAdmissionClass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtPrevSchool = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Session = new com.toedter.calendar.JYearChooser();
        lblImage = new javax.swing.JLabel();
        btnPassport = new javax.swing.JButton();
        RegDate = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        EndDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtClass = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CMale = new javax.swing.JCheckBox();
        CFemale = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        CYes = new javax.swing.JCheckBox();
        CNo = new javax.swing.JCheckBox();
        PhysicalDis = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Medical = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        DisabilityType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnRetrieve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Student ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, -1));

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 51, 51));
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 310, 20));

        txtAdmissionClass.setBackground(new java.awt.Color(255, 255, 255));
        txtAdmissionClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAdmissionClass.setForeground(new java.awt.Color(51, 51, 51));
        txtAdmissionClass.setBorder(null);
        jPanel1.add(txtAdmissionClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 140, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Admission Class");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 110, -1));

        jSeparator12.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator12.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 310, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 140, -1));

        txtPrevSchool.setBackground(new java.awt.Color(255, 255, 255));
        txtPrevSchool.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPrevSchool.setForeground(new java.awt.Color(51, 51, 51));
        txtPrevSchool.setBorder(null);
        jPanel1.add(txtPrevSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 310, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Previous School");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 110, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 310, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Session");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        Session.setBackground(new java.awt.Color(255, 255, 255));
        Session.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Session, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 140, 30));

        lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 220, 200));

        btnPassport.setBackground(new java.awt.Color(255, 255, 255));
        btnPassport.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnPassport.setForeground(new java.awt.Color(0, 102, 204));
        btnPassport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Add.png"))); // NOI18N
        btnPassport.setText("Add Passport");
        btnPassport.setToolTipText("Add Passport");
        btnPassport.setBorder(null);
        btnPassport.setBorderPainted(false);
        btnPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassportActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 130, 40));

        RegDate.setBackground(new java.awt.Color(255, 255, 255));
        RegDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(RegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 140, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Registration Date");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        EndDate.setBackground(new java.awt.Color(255, 255, 255));
        EndDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EndDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(EndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 140, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("End Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator4.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 310, -1));

        txtClass.setBackground(new java.awt.Color(255, 255, 255));
        txtClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtClass.setForeground(new java.awt.Color(51, 51, 51));
        txtClass.setBorder(null);
        jPanel1.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 310, 20));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Previous Class");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Gender");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        buttonGroup1.add(CMale);
        CMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMale.setText("Male");
        CMale.setBorderPainted(true);
        jPanel1.add(CMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        buttonGroup1.add(CFemale);
        CFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CFemale.setText("Female");
        CFemale.setBorderPainted(true);
        CFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(CFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Password");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 230, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 230, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("STUDENT MANAGEMENT(Update)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 26));

        jSeparator5.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator5.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 970, 10));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Disability ?");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        buttonGroup2.add(CYes);
        CYes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CYes.setText("Yes");
        CYes.setBorderPainted(true);
        jPanel1.add(CYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        buttonGroup2.add(CNo);
        CNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CNo.setText("No");
        CNo.setBorderPainted(true);
        CNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(CNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        PhysicalDis.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        PhysicalDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Arthritis", "Back injury", "Amputation", "Spina bifida", "Cerebral palsy", "Multiple sclerosis", "Spinal cord injury", "Muscular dystrophy", "Others" }));
        jPanel1.add(PhysicalDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 310, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Physical Disabilities");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        Medical.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Medical.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Anxiety", "Obesity", "Diabetes", "Back pain", "Allergic rhinitis", "Hypertention", "Reflux esophagitis", "Hyperlipidemia", "Others" }));
        jPanel1.add(Medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 310, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Medical Condition");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 130, -1));

        DisabilityType.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        DisabilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Vision", "Hearing", "Thinking", "Learning", "Movement", "Mental health", "Communicating", "Social relationships", "Others" }));
        jPanel1.add(DisabilityType, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 310, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Disability Type");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 100, -1));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 102, 204));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("Sign up");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 80, 40));

        btncancel.setBackground(new java.awt.Color(255, 255, 255));
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(0, 102, 204));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Cancel.png"))); // NOI18N
        btncancel.setText("Cancel");
        btncancel.setToolTipText("Cancel");
        btncancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 90, 40));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(51, 51, 51));
        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 100, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Full Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 80, -1));

        lblError.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 110, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Health Condition");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, 26));

        btnRetrieve.setBackground(new java.awt.Color(255, 255, 255));
        btnRetrieve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRetrieve.setForeground(new java.awt.Color(0, 102, 204));
        btnRetrieve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Data_Recovery1.png"))); // NOI18N
        btnRetrieve.setText("Retrieve");
        btnRetrieve.setToolTipText("Retrieve");
        btnRetrieve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassportActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("*.image", "jpg", "gif", "png");
        chooser.addChoosableFileFilter(extensionFilter);
        int result = chooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lblImage.setIcon(resizeImage(path));
            s = path;
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No Data");
        }

    }//GEN-LAST:event_btnPassportActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        handler = new DBHandler();
        String update = "UPDATE student_details SET StudentName=?,Gender=?,PreviousSchool=?,PreviousClass=?,AdmissionClass=?,"
                + "Session=?,PhysicalDisability=?,DisabilityType=?,MedicalCondition=?,Passport=?,Disability=?,RegDate=?,EndDate=?,Password=?"
                + "WHERE StudentID=?";

        try {
            try (PreparedStatement pst = handler.getdbConnection().prepareStatement(update)) {

                pst.setString(1, txtName.getText());

                String gender;
                if (CMale.isSelected()) {
                    gender = "Male";
                } else {
                    gender = "Female";
                }
                pst.setString(2, gender);
                pst.setString(3, txtPrevSchool.getText());
                pst.setString(4, txtClass.getText());
                pst.setString(5, txtAdmissionClass.getText());
                pst.setInt(6, Session.getYear());
                pst.setString(7, (String) PhysicalDis.getSelectedItem());
                pst.setString(8, (String) DisabilityType.getSelectedItem());
                pst.setString(9, (String) Medical.getSelectedItem());

                input = new FileInputStream(new File(s));
                pst.setBlob(10, input);

                String disability;
                if (CYes.isSelected()) {
                    disability = "Yes";
                } else {
                    disability = "No";
                }

                pst.setString(11, disability);
                pst.setDate(12, convertUtilDateToSqlDate(RegDate.getDate()));
                pst.setDate(13, convertUtilDateToSqlDate(EndDate.getDate()));
                pst.setString(14, txtPassword.getText());
                pst.setString(15, txtID.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Saved");
                pst.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(StudentSignup.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentSignup.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed

        this.dispose();

    }//GEN-LAST:event_btncancelActionPerformed

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed

        String id = txtID.getText();
        String name = txtName.getText();
        String preSchool = txtPrevSchool.getText();
        String preClass = txtClass.getText();
        String admClass = txtAdmissionClass.getText();
        int session = Session.getYear();
        String regDate = RegDate.getDateFormatString();
        String endDate = EndDate.getDateFormatString();
        String pass = txtPassword.getText();
        String medical = (String) Medical.getSelectedItem();
        String phyDis = (String) PhysicalDis.getSelectedItem();
        String disType = (String) DisabilityType.getSelectedItem();
        String disYes = CYes.getText();
        String disNo = CNo.getText();
        String male = CMale.getText();
        String female = CFemale.getText();

        handler = new DBHandler();
        ResultSet rs = null;
        if (!id.equals("")) {
            String select = "SELECT * FROM student_details WHERE StudentID = ?";
            try {
                PreparedStatement pst = handler.getdbConnection().prepareStatement(select);
                pst.setString(1, id);
                int counter = 0;
                rs = pst.executeQuery();
                if (rs.next()) {
                    counter++;
                    name = rs.getString("StudentName");
                    preSchool = rs.getString("PreviousSchool");
                    preClass = rs.getString("PreviousClass");
                    admClass = rs.getString("AdmissionClass");
                    session = rs.getInt("Session");
                    regDate = rs.getString("RegDate");
                    endDate = rs.getString("EndDate");
                    pass = rs.getString("Password");
                    medical = rs.getString("MedicalCondition");
                    phyDis = rs.getString("PhysicalDisability");
                    disType = rs.getString("DisabilityType");
                    bufferedImage = ImageIO.read(rs.getBinaryStream("Passport"));
                    if (disNo.equals(rs.getString("Disability"))) {
                        disNo = "No";
                    } else {
                        disYes = "Yes";
                    }
                    if (male.equals(rs.getString("Gender"))) {
                        male = "Male";
                    } else {
                        female = "Female";
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No Student ID as " + id);
                    JTextField temp = null;
                    for (Component C : jPanel1.getComponents()) {
                        if (C.getClass().toString().contains("javax.swing.JTextField")) {

                            temp = (JTextField) C;
                            temp.setText(null);
                        }
                    }
                    txtPassword.setText("");
                    Session.setName("0");
                    RegDate.setDateFormatString("");
                    EndDate.setDateFormatString("");
                    lblImage.setText("");
                    lblImage.setIcon(null);
                }

                if (counter == 1) {
                    txtName.setText(name);
                    txtPrevSchool.setText(preSchool);
                    txtClass.setText(preClass);
                    txtAdmissionClass.setText(admClass);
                    Session.setYear(session);
//                    convertUtilDateToSqlDate(RegDate.getDate());
//                    convertUtilDateToSqlDate(EndDate.getDate());
                    RegDate.setDateFormatString(regDate);
                    EndDate.setDateFormatString(endDate);
                    txtPassword.setText(pass);
                    Medical.setSelectedItem(medical);
                    PhysicalDis.setSelectedItem(phyDis);
                    DisabilityType.setSelectedItem(disType);
                    CNo.setText(disNo);
                    CYes.setText(disYes);
                    CMale.setText(male);
                    CFemale.setText(female);

                    imageIcon = new ImageIcon(new ImageIcon(bufferedImage).getImage().getScaledInstance(lblImage.getWidth(),
                            lblImage.getHeight(), Image.SCALE_DEFAULT));
                    lblImage.setIcon(imageIcon);
                    lblError.setText("");

                } else {
                    JOptionPane.showMessageDialog(this, "Can't retrieve data !");
                }

            } catch (ClassNotFoundException | SQLException | IOException ex) {
                Logger.getLogger(StudentMgt.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            lblError.setText("ID is needed !");

            JTextField temp = null;
            for (Component C : jPanel1.getComponents()) {
                if (C.getClass().toString().contains("javax.swing.JTextField")) {
                    temp = (JTextField) C;
                    temp.setText(null);
                }
            }
            txtPassword.setText("");
            Session.setName("0");
            RegDate.setDateFormatString("");
            EndDate.setDateFormatString("");
            lblImage.setIcon(null);
        }


    }//GEN-LAST:event_btnRetrieveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentMgt().setVisible(true);
        });
    }

    //Getting image size
    public ImageIcon resizeImage(String imgPath) {
        ImageIcon myImage = new ImageIcon(imgPath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);

        return image;

    }

    private java.sql.Date convertUtilDateToSqlDate(java.util.Date date) {
        if (date != null) {
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CFemale;
    private javax.swing.JCheckBox CMale;
    private javax.swing.JCheckBox CNo;
    private javax.swing.JCheckBox CYes;
    private javax.swing.JComboBox<String> DisabilityType;
    private com.toedter.calendar.JDateChooser EndDate;
    private javax.swing.JComboBox<String> Medical;
    private javax.swing.JComboBox<String> PhysicalDis;
    private com.toedter.calendar.JDateChooser RegDate;
    private com.toedter.calendar.JYearChooser Session;
    private javax.swing.JButton btnPassport;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btncancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtAdmissionClass;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPrevSchool;
    // End of variables declaration//GEN-END:variables
}
