/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import schoolmgtsystem.dbhelper.DBHandler;

/**
 *
 * @author FabulousTHO
 */
public class StudentSignup extends javax.swing.JFrame {

    String s;
//    PreparedStatement preparedStatement;
//    String conStr = "jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=SchoolManagementSystem;user=sa;password=123456789";

    /**
     * Creates new form TeacherLogIn
     */
    public StudentSignup() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAdmissionClass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtClass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrevSchool = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CMale = new javax.swing.JCheckBox();
        CFemale = new javax.swing.JCheckBox();
        btnsignup = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        Session = new com.toedter.calendar.JYearChooser();
        jLabel13 = new javax.swing.JLabel();
        CYes = new javax.swing.JCheckBox();
        CNo = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EndDate = new com.toedter.calendar.JDateChooser();
        RegDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnPassport = new javax.swing.JButton();
        Medical = new javax.swing.JComboBox<>();
        PhysicalDis = new javax.swing.JComboBox<>();
        DisabilityType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_User_Groups_104px_1.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Student");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 256, 10));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 232, 10));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 184, 10));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 142, 10));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 116, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 650));

        jSeparator12.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator12.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 310, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 310, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 310, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 310, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator5.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 530, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Disability Type");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 100, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Physical Disabilities");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Session");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        txtAdmissionClass.setBackground(new java.awt.Color(255, 255, 255));
        txtAdmissionClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAdmissionClass.setForeground(new java.awt.Color(51, 51, 51));
        txtAdmissionClass.setBorder(null);
        jPanel1.add(txtAdmissionClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 310, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Admission Class");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 110, -1));

        txtClass.setBackground(new java.awt.Color(255, 255, 255));
        txtClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtClass.setForeground(new java.awt.Color(51, 51, 51));
        txtClass.setBorder(null);
        jPanel1.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 310, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("End Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        txtPrevSchool.setBackground(new java.awt.Color(255, 255, 255));
        txtPrevSchool.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPrevSchool.setForeground(new java.awt.Color(51, 51, 51));
        txtPrevSchool.setBorder(null);
        jPanel1.add(txtPrevSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 310, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Previous School");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 110, -1));

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 51, 51));
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 310, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("Full Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Health Condition");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, 26));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("Gender");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        buttonGroup1.add(CMale);
        CMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMale.setText("Male");
        CMale.setBorderPainted(true);
        jPanel1.add(CMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        buttonGroup1.add(CFemale);
        CFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CFemale.setText("Female");
        CFemale.setBorderPainted(true);
        CFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(CFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        btnsignup.setBackground(new java.awt.Color(0, 102, 204));
        btnsignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setText("SignUp");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 120, 36));

        btncancel.setBackground(new java.awt.Color(0, 102, 204));
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 120, 36));

        Session.setBackground(new java.awt.Color(255, 255, 255));
        Session.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Session, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 140, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("Sign Up ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, 26));

        buttonGroup2.add(CYes);
        CYes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CYes.setText("Yes");
        CYes.setBorderPainted(true);
        jPanel1.add(CYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        buttonGroup2.add(CNo);
        CNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CNo.setText("No");
        CNo.setBorderPainted(true);
        CNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(CNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 204));
        jLabel14.setText("Disability ?");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Class");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 204));
        jLabel16.setText("Registration Date");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));

        EndDate.setBackground(new java.awt.Color(255, 255, 255));
        EndDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EndDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(EndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 140, 30));

        RegDate.setBackground(new java.awt.Color(255, 255, 255));
        RegDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(RegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 140, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setText("Medical Condition");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 130, -1));

        lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 220, 200));

        btnPassport.setBackground(new java.awt.Color(0, 153, 204));
        btnPassport.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnPassport.setForeground(new java.awt.Color(255, 255, 255));
        btnPassport.setText("Add Passport");
        btnPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassportActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 120, 30));

        Medical.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Medical.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Anxiety", "Obesity", "Diabetes", "Back pain", "Allergic rhinitis", "Hypertention", "Reflux esophagitis", "Hyperlipidemia", "Others" }));
        jPanel1.add(Medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 310, 30));

        PhysicalDis.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        PhysicalDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Arthritis", "Back injury", "Amputation", "Spina bifida", "Cerebral palsy", "Multiple sclerosis", "Spinal cord injury", "Muscular dystrophy", "Others" }));
        jPanel1.add(PhysicalDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 310, 30));

        DisabilityType.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        DisabilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Vision", "Hearing", "Thinking", "Learning", "Movement", "Mental health", "Communicating", "Social relationships", "Others" }));
        jPanel1.add(DisabilityType, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 310, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed

        DBHandler handler = new DBHandler();
        String insert = "INSERT INTO student_details(StudentName,Gender,PreviousSchool,PreviousClass,AdmissionClass,"
                + "Session,PhysicalDisability,DisabilityType,MedicalCondition,Passport,Disability,RegDate,EndDate) "
                + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";

        try {
            try (PreparedStatement pst = handler.getdbConnection().prepareStatement(insert)) {
                InputStream input = new FileInputStream(new File(s));
                pst.setString(1, txtName.getText());

                String gender;
                if (CMale.isSelected()) {
                    gender = "Male";
                } else {
                    gender = "Female";
                }
                pst.setString(2, gender);
                pst.setString(3, txtPrevSchool.getText());
                pst.setString(4, txtClass.getText());
                pst.setString(5, txtAdmissionClass.getText());
                pst.setInt(6, Session.getYear());
                pst.setString(7, (String) PhysicalDis.getSelectedItem());
                pst.setString(8, (String) DisabilityType.getSelectedItem());
                pst.setString(9, (String) Medical.getSelectedItem());
                pst.setBlob(10, input);

                String disability;
                if (CYes.isSelected()) {
                    disability = "Yes";
                } else {
                    disability = "No";
                }

                pst.setString(11, disability);
                pst.setDate(12, convertUtilDateToSqlDate(RegDate.getDate()));
                pst.setDate(13, convertUtilDateToSqlDate(EndDate.getDate()));

                int count = pst.executeUpdate();
                JOptionPane.showMessageDialog(this, count + "Successful");

            } catch (FileNotFoundException ex) {
                Logger.getLogger(StudentSignup.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentSignup.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassportActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("*.image", "jpg", "gif", "png");
        chooser.addChoosableFileFilter(extensionFilter);
        int result = chooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lblImage.setIcon(resizeImage(path));
            s = path;
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No Data");
        }


    }//GEN-LAST:event_btnPassportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentSignup().setVisible(true);
        });
    }

//    public void populateListView() {
//
//        DBHandler handler = new DBHandler();
//
//        String str = "SELECT FirstName, Surname FROM StudentReg WHERE Email = ?";
//        try {
//            PreparedStatement pst = handler.getdbConnection().prepareStatement(str);
//
//            ListView list = new ListView();
//
//            ResultSet rs = pst.executeQuery();
//            while (rs.next()) {
//
//                list.show();
//
//            }
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(StudentSignup.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//    }
//    public ResultSet getID() {
//        ResultSet result = null;
//        if
//        
//        return result;
//    }
    public ImageIcon resizeImage(String imgPath) {
        ImageIcon myImage = new ImageIcon(imgPath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);

        return image;

    }

    private java.sql.Date getCurrentDate() {
        java.util.Date today = new java.util.Date();
        return new java.sql.Date(today.getYear());
    }

    private java.sql.Date convertUtilDateToSqlDate(java.util.Date date) {
        if (date != null) {
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CFemale;
    private javax.swing.JCheckBox CMale;
    private javax.swing.JCheckBox CNo;
    private javax.swing.JCheckBox CYes;
    private javax.swing.JComboBox<String> DisabilityType;
    private com.toedter.calendar.JDateChooser EndDate;
    private javax.swing.JComboBox<String> Medical;
    private javax.swing.JComboBox<String> PhysicalDis;
    private com.toedter.calendar.JDateChooser RegDate;
    private com.toedter.calendar.JYearChooser Session;
    private javax.swing.JButton btnPassport;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsignup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtAdmissionClass;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrevSchool;
    // End of variables declaration//GEN-END:variables
}
