/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import schoolmgtsystem.model.dbhelper.DBHandler;

/**
 *
 * @author Thomas
 */
public class StudentResult_Nursery extends javax.swing.JFrame {

    DBHandler handler;

    /**
     * Creates new form ResultNursery
     */
    public StudentResult_Nursery() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtTotalScore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHealth = new javax.swing.JTextField();
        txtSocial = new javax.swing.JTextField();
        txtElem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSound = new javax.swing.JTextField();
        txtEnglish = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtComputer = new javax.swing.JTextField();
        txtVerbal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtWriting = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtRhymes = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtArts = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtMoral = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtQuan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTranscript = new javax.swing.JTextArea();
        btnRanking = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "NURSERY SCHOOL RESULT RECORDS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 107, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 107, -1));

        txtFullName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 290, -1));

        txtTotalScore.setEditable(false);
        txtTotalScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotalScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalScoreActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total Score");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 107, -1));

        txtAverage.setEditable(false);
        txtAverage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAverage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Average");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 107, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Social Habits");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Health Habits");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 130, -1));

        txtHealth.setEditable(false);
        txtHealth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtHealth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 90, -1));

        txtSocial.setEditable(false);
        txtSocial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSocial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 90, -1));

        txtElem.setEditable(false);
        txtElem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtElem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtElem, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Elementary Science");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Sound & Read");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 130, -1));

        txtSound.setEditable(false);
        txtSound.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSound.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtSound, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 90, -1));

        txtEnglish.setEditable(false);
        txtEnglish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEnglish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 90, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("English");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 107, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 326, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Position");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 107, -1));

        txtPosition.setEditable(false);
        txtPosition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Computer");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 100, -1));

        txtComputer.setEditable(false);
        txtComputer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtComputer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 90, -1));

        txtVerbal.setEditable(false);
        txtVerbal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtVerbal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVerbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerbalActionPerformed(evt);
            }
        });
        jPanel1.add(txtVerbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Verbal Reasoning");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 170, -1));

        txtWriting.setEditable(false);
        txtWriting.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtWriting.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtWriting, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 90, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Writing");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 80, -1));

        txtStudentID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtStudentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Nursery Rhymes");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 150, -1));

        txtRhymes.setEditable(false);
        txtRhymes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtRhymes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRhymes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 90, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Cultural Arts");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 120, -1));

        txtArts.setEditable(false);
        txtArts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtArts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtArts, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 90, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Moral Instruction");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 160, -1));

        txtMoral.setEditable(false);
        txtMoral.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMoral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 90, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Quantitative R.");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 140, -1));

        txtQuan.setEditable(false);
        txtQuan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQuan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 90, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 810, 590));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "Result Printout", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        txtTranscript.setEditable(false);
        txtTranscript.setColumns(20);
        txtTranscript.setRows(5);
        jScrollPane1.setViewportView(txtTranscript);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 380, 590));

        btnRanking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRanking.setText("Ranking");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        jPanel4.add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, -1, -1));

        btnTranscript.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });
        jPanel4.add(btnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, -1, -1));

        btnGenerate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel4.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, -1, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Left_30px_1.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        btnExit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalScoreActionPerformed

    private void txtVerbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerbalActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        double[] R = new double[14];

        R[0] = Double.parseDouble(txtEnglish.getText());
        R[1] = Double.parseDouble(txtSound.getText());
        R[2] = Double.parseDouble(txtElem.getText());
        R[3] = Double.parseDouble(txtSocial.getText());
        R[4] = Double.parseDouble(txtHealth.getText());
        R[5] = Double.parseDouble(txtComputer.getText());
        R[6] = Double.parseDouble(txtArts.getText());
        R[7] = Double.parseDouble(txtWriting.getText());
        R[8] = Double.parseDouble(txtRhymes.getText());
        R[9] = Double.parseDouble(txtVerbal.getText());
        R[10] = Double.parseDouble(txtQuan.getText());
        R[11] = Double.parseDouble(txtMoral.getText());

        R[12] = (R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7] + R[8] + R[9] + R[10] + R[11]) / 12;
        //R[9] = (R[0] + R[1] + R[2] + R[3] + R[5] + R[6] + R[7])/7;
        R[13] = R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7] + R[8] + R[9] + R[10] + R[11];

        String Average = String.format("%.0f", R[12]);
        txtAverage.setText(Average);

        String TotalScore = String.format("%.0f", R[13]);
        txtTotalScore.setText(TotalScore);

        if (R[13] >= 100) {
            txtPosition.setText("1st");
        } else if (R[13] >= 90) {
            txtPosition.setText("2nd");
        } else if (R[13] >= 80) {
            txtPosition.setText("3rd");
        } else if (R[13] >= 70) {
            txtPosition.setText("4th");
        } else if (R[13] >= 60) {
            txtPosition.setText("5th");
        } else if (R[13] >= 50) {
            txtPosition.setText("Average");
        } else if (R[13] >= 40) {
            txtPosition.setText("Fail");
        }
        //else if (R[10] >= 100){
        //txtRanking.setText("Poor");
        //}
        //else if (R[10] >= 50){
        // txtRanking.setText("Fail");
        //}

//       txtMoral    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //        model.addRow(new Object[]{
        //            txtStudentID.getText(),
        //            txtFirstName.getText(),
        //            txtSurname.getText(),
        //            txtCourseCode.getSelectedItem(),
        //            txtMaths.getText(),
        //            txtEnglish.getText(),
        //            txtLit.getText(),
        //            txtBS.getText(),
        //            txtBT.getText(),
        //            txtPHE.getText(),
        //            txtICT.getText(),
        //            txtCRS.getText(),
        //            txtSocial.getText(),
        //            txtTotalScore.getText(),
        //            txtAverage.getText(),
        //            txtPosition.getText()
        //        });
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
        txtTranscript.append("BRIGHT STARS SCHOOL"
                + "\n\tStudent Result"
                + "\n_____________________________________"
                + "\nStudent ID:\t\t" + txtStudentID.getText()
                + "\n_____________________________________"
                + "\nFirst Name:\t\t" + txtFullName.getText()
                + "\n_____________________________________"
                + "\nEnglish:\t\t" + txtEnglish.getText()
                + "\n_____________________________________"
                + "\nSound & Read:\t\t" + txtSound.getText()
                + "\n_____________________________________"
                + "\nElementary Science:\t\t" + txtElem.getText()
                + "\n_____________________________________"
                + "\nSocial Habits:\t" + txtSocial.getText()
                + "\n_____________________________________"
                + "\nHealth Habits:\t" + txtHealth.getText()
                + "\n_____________________________________"
                + "\nComputer:\t" + txtComputer.getText()
                + "\n_____________________________________"
                + "\nVerbal:\t\t" + txtVerbal.getText()
                + "\n_____________________________________"
                + "\nWriting:\t\t" + txtWriting.getText()
                + "\n_____________________________________"
                + "\nNursery Rhymes:\t\t" + txtRhymes.getText()
                + "\n_____________________________________"
                + "\nCreative Arts:\t" + txtArts.getText()
                + "\n_____________________________________"
                + "\nQuantitative R..:\t" + txtQuan.getText()
                + "\n_____________________________________"
                + "\nTotal Score:\t\t" + txtTotalScore.getText()
                + "\n_____________________________________"
                + "\nAverage:\t\t" + txtAverage.getText()
                + "\n_____________________________________"
                + "\nPosition:\t\t" + txtPosition.getText()
                + "\n_____________________________________"
        );


    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        try {

            handler = new DBHandler();

            String str = "select * from nursery where StudentID = ?";
            try {
                PreparedStatement preparedStatement = handler.getdbConnection().prepareStatement(str);
                preparedStatement.setString(1, txtStudentID.getText());

                ResultSet rs = preparedStatement.executeQuery();

                while (rs.next()) {

                    txtStudentID.setText(rs.getString("StudentID"));
                    txtEnglish.setText(rs.getString("English_Total"));
                    txtSound.setText(rs.getString("Sound_Total"));
                    txtElem.setText(rs.getString("ES_Total"));
                    txtSocial.setText(rs.getString("Social_Total"));
                    txtHealth.setText(rs.getString("Health_Total"));
                    txtComputer.setText(rs.getString("Computer_Total"));
                    txtArts.setText(rs.getString("CCA_Total"));
                    txtWriting.setText(rs.getString("Writing_Total"));
                    txtRhymes.setText(rs.getString("Rhymes_Total"));
                    txtVerbal.setText(rs.getString("Verbal_Total"));
                    txtQuan.setText(rs.getString("Quan_Total"));
                    txtMoral.setText(rs.getString("Moral_Total"));

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ResultSSS.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        JTextField temp = null;
        for (Component C : jPanel1.getComponents()) {
            if (C.getClass().toString().contains("javax.swing.JTextField")) {

                temp = (JTextField) C;
                temp.setText(null);

                JTextArea tem = null;
                for (Component A : jPanel1.getComponents()) {
                    if (A.getClass().toString().contains("javax.swing.JTextArea")) {

                        tem = (JTextArea) A;
                        tem.setText(null);
                    }
                    txtTranscript.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int sel = JOptionPane.showConfirmDialog(this, "Do you want to print Result?");
        if (sel == 0) {
            try {
                printResult();
            } catch (IOException ex) {
                Logger.getLogger(StudentResult_Nursery.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (sel == 1) {
            new StudentResult_Nursery().show();
            this.dispose();
        }
        if (sel == 2) {
            new StudentResult_Nursery().show();
            this.dispose();
        }

    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResult_Nursery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResult_Nursery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResult_Nursery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResult_Nursery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentResult_Nursery().setVisible(true);
        });
    }

    public void printResult() throws IOException {

        //PreparedStatement to get the 1st and 2nd Test score
        String str = "select * from nursery where StudentID = ?";

        handler = new DBHandler();

        String english1 = null, english2 = null, englishE = null, sound1 = null, sound2 = null, soundE = null, es1 = null,
                es2 = null, esE = null, social1 = null, social2 = null, socialE = null, health1 = null, health2 = null, healthE = null,
                com1 = null, com2 = null, comE = null, cca1 = null, cca2 = null, ccaE = null, writing1 = null, writing2 = null, writingE = null,
                rhymes1 = null, rhymes2 = null, rhymesE = null, verbal1 = null, verbal2 = null, verbalE = null, quan1 = null, quan2 = null,
                quanE = null, moral1 = null, moral2 = null, moralE = null;

        try {
            PreparedStatement pst = handler.getdbConnection().prepareStatement(str);

//             Statement pst = handler.getdbConnection().createStatement();
            pst.setString(1, txtStudentID.getText());

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                txtStudentID.setText(rs.getString("StudentID"));
                english1 = rs.getString("English1");
                english2 = rs.getString("English2");
                englishE = rs.getString("English_Exam");
                sound1 = rs.getString("Sound1");
                sound2 = rs.getString("Sound2");
                soundE = rs.getString("Sound_Exam");
                es1 = rs.getString("ES1");
                es2 = rs.getString("ES2");
                esE = rs.getString("ES_Exam");
                social1 = rs.getString("Social1");
                social2 = rs.getString("Social2");
                socialE = rs.getString("Social_Exam");
                health1 = rs.getString("Health1");
                health2 = rs.getString("Health2");
                healthE = rs.getString("Health_Exam");
                com1 = rs.getString("Computer1");
                com2 = rs.getString("Computer2");
                comE = rs.getString("Computer_Exam");
                cca1 = rs.getString("CCA1");
                cca2 = rs.getString("CCA2");
                ccaE = rs.getString("CCA_Exam");
                writing1 = rs.getString("Writing1");
                writing2 = rs.getString("Writing2");
                writingE = rs.getString("Writing_Exam");
                rhymes1 = rs.getString("Rhymes1");
                rhymes2 = rs.getString("Rhymes2");
                rhymesE = rs.getString("Rhymes_Exam");
                verbal1 = rs.getString("Verbal1");
                verbal2 = rs.getString("Verbal2");
                verbalE = rs.getString("Verbal_Exam");
                quan1 = rs.getString("Quan1");
                quan2 = rs.getString("Quan2");
                quanE = rs.getString("Quan_Exam");
                moral1 = rs.getString("Moral1");
                moral2 = rs.getString("Moral2");
                moralE = rs.getString("Moral_Exam");

            }

            System.out.println("1st Test " + english1);
            System.out.println("2st Test " + english2);
            System.out.println("Exam " + englishE);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentResult_Nursery.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Creating a file dialog with file chooser
        //Prints out file in PDF format
        JFileChooser chooser = new JFileChooser();
        chooser.showSaveDialog(this);
        chooser.getSelectedFile();

        File file = chooser.getSelectedFile();

        Document document = new Document();
        Font font = new Font();

        try {

            String english_total = txtEnglish.getText();
            String sound_total = txtSound.getText();
            String elem_total = txtElem.getText();
            String social_total = txtSocial.getText();
            String health_total = txtHealth.getText();
            String computer_total = txtComputer.getText();
            String cca_total = txtArts.getText();
            String writing_total = txtWriting.getText();
            String rhymes_total = txtRhymes.getText();
            String verbal_total = txtVerbal.getText();
            String quan_total = txtQuan.getText();
            String moral_total = txtMoral.getText();
            String score_total = txtTotalScore.getText();
            String average_total = txtAverage.getText();
            String position_total = txtPosition.getText();

            System.out.println("English Total " + english_total);

            PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(file));
            document.open();

//            document.add(new Paragraph(content));
//            document.add(new Paragraph(title));
            Image image = Image.getInstance("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\SchoolMgtSystem\\Bright_Stars.png");
            image.setAbsolutePosition(70, 738);

            Font infofont = new Font(Font.FontFamily.TIMES_ROMAN, 11.5f, Font.BOLD);
            Font detailsfont = new Font(Font.FontFamily.HELVETICA, 11f, Font.NORMAL);
            Font namefont = new Font(Font.FontFamily.TIMES_ROMAN, 12.5f, Font.BOLD);
            Font motofont = new Font(Font.FontFamily.TIMES_ROMAN, 9, Font.BOLD);

            Paragraph ti = new Paragraph("", namefont);
            ti.add("BRIGHT STARS NURSERY SCHOOL");
            ti.setAlignment(Element.ALIGN_CENTER);
//            font = ti.getFont();
//            font.setSize(12.5f);

            Paragraph sl = new Paragraph("", motofont);
            sl.add("(NURSERY, PRIMARY & SECONDARY)");
            sl.setAlignment(Element.ALIGN_CENTER);
            font = sl.getFont();
            font.setSize(10);
            sl.setSpacingBefore(0f);
            sl.setSpacingAfter(0f);

            Paragraph sti = new Paragraph("", infofont);
            sti.add("Omorodion Osaretin Str, Off Okuwague\nEvbabogun Road, Off Sapele Road, Benin City");
            sti.setAlignment(Element.ALIGN_CENTER);
            sti.setSpacingBefore(0f);
            sti.setSpacingAfter(0f);

            Paragraph tele = new Paragraph("", infofont);
            tele.add("TEL: 07067183000" + " \tEmail: informbrightstars@yahoo.com");
            tele.setAlignment(Element.ALIGN_CENTER);
            tele.setSpacingBefore(0f);
            tele.setSpacingAfter(0f);

            Paragraph mot = new Paragraph("", infofont);
            mot.add("MOTTO: Knowledge for Excellence");
            mot.setAlignment(Element.ALIGN_CENTER);
            mot.setSpacingBefore(0f);
            mot.setSpacingAfter(0f);

            Paragraph name = new Paragraph("", detailsfont);
            name.setAlignment(Element.ALIGN_CENTER);
            name.add("Name of pupil: " + txtFullName.getText()
                    + "   Sex: ____" + "   Age: ____" + "   Adm NO: " + txtStudentID.getText());
            name.setSpacingBefore(8f);

            Paragraph house = new Paragraph("", detailsfont);
            house.setAlignment(Element.ALIGN_CENTER);
            house.add("Assessment for: __________"
                    + " Term: ________" + " Class: __________" + " NO In class: ______" /*+ " Position: _______"*/);
            house.setSpacingBefore(5f);
//            house.setSpacingAfter(10f);

            Paragraph pos = new Paragraph("", detailsfont);
            pos.setAlignment(Element.ALIGN_CENTER);
            pos.add("Position: " + position_total + " School House: ________" + " 20___ / 20___ session  Attendance ____ Out of ____");
            pos.setSpacingBefore(5f);
//            pos.setSpacingAfter(10f);

            Paragraph res = new Paragraph("", detailsfont);
            res.setAlignment(Element.ALIGN_CENTER);
            res.add("Resumption: _________________");
            res.setSpacingBefore(5f);
            res.setSpacingAfter(8f);

//            Paragraph img = new Paragraph();
//            img.add(Image.getInstance("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\SchoolMgtSystem\\Bright_Stars.png"));
//            img.setAlignment(Element.ALIGN_CENTER);
            //Adding to the Document
            document.add(image);
            document.add(ti);
            document.add(sl);
            document.add(sti);
            document.add(tele);
            document.add(mot);
            document.add(name);
            document.add(house);
            document.add(pos);
            document.add(res);

//            document.add(new Paragraph(subTitle));
//            document.add(new Paragraph("Student ID: " + txtStudentID.getText()));
//            document.add(new Paragraph("First Name: " + txtFullName.getText()));
//            document.add(new Paragraph("Surname: " + txtSurname.getText()));
//            document.add(new Paragraph("Course Code: " + txtCourseCode.getSelectedItem()));
//            document.add(new Paragraph("DETAILED RESULT"));
            PdfPTable table = new PdfPTable(10);
            table.setWidthPercentage(105);
            table.setSpacingBefore(11f);
            table.setSpacingAfter(5f);

            float[] colWidth = {0.2f, 2f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f};
            table.setWidths(colWidth);

//            DEFINING FONT SIZES FOR THE TABLE HEADER ANND TABLE CELLS
            Font headerfont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);
            Font cellfont = new Font(Font.FontFamily.HELVETICA, 10.8f, Font.NORMAL);

            PdfPCell c1 = new PdfPCell(new Paragraph("", headerfont));
            PdfPCell c2 = new PdfPCell(new Paragraph("", headerfont));
            PdfPCell c3 = new PdfPCell(new Paragraph(" MAX\n 100", headerfont));
            PdfPCell c4 = new PdfPCell(new Paragraph(" 1ST TEST\n  20", headerfont));
            PdfPCell c5 = new PdfPCell(new Paragraph(" 2ND TEST\n  20", headerfont));
            PdfPCell c6 = new PdfPCell(new Paragraph("EXAM\n  60", headerfont));
            PdfPCell c7 = new PdfPCell(new Paragraph("TOTAL\n  100", headerfont));
            PdfPCell c8 = new PdfPCell(new Paragraph("POSITION", headerfont));
            PdfPCell c9 = new PdfPCell(new Paragraph("REMARKS", headerfont));
            PdfPCell c10 = new PdfPCell(new Paragraph("SIGN", headerfont));

            PdfPCell en1 = new PdfPCell(new Paragraph("1", cellfont));
            PdfPCell en2 = new PdfPCell(new Paragraph("ENGLISH STUDIES", cellfont));
            PdfPCell en3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell en4 = new PdfPCell(new Paragraph("  " + english1, cellfont));
            PdfPCell en5 = new PdfPCell(new Paragraph("  " + english2, cellfont));
            PdfPCell en6 = new PdfPCell(new Paragraph("  " + englishE, cellfont));
            PdfPCell en7 = new PdfPCell(new Paragraph("  " + english_total, cellfont));
            PdfPCell en8 = new PdfPCell(new Paragraph(""));
            PdfPCell en9 = new PdfPCell(new Paragraph(""));
            PdfPCell en10 = new PdfPCell(new Paragraph(""));

            PdfPCell s1 = new PdfPCell(new Paragraph("2", cellfont));
            PdfPCell s2 = new PdfPCell(new Paragraph("SOUND & READ (PHONICS)", cellfont));
            PdfPCell s3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell s4 = new PdfPCell(new Paragraph("  " + sound1, cellfont));
            PdfPCell s5 = new PdfPCell(new Paragraph("  " + sound2, cellfont));
            PdfPCell s6 = new PdfPCell(new Paragraph("  " + soundE, cellfont));
            PdfPCell s7 = new PdfPCell(new Paragraph("  " + sound_total, cellfont));
            PdfPCell s8 = new PdfPCell(new Paragraph(""));
            PdfPCell s9 = new PdfPCell(new Paragraph(""));
            PdfPCell s10 = new PdfPCell(new Paragraph(""));

            PdfPCell e1 = new PdfPCell(new Paragraph("3", cellfont));
            PdfPCell e2 = new PdfPCell(new Paragraph("ELEMENTARY SCIENCE", cellfont));
            PdfPCell e3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell e4 = new PdfPCell(new Paragraph("  " + es1, cellfont));
            PdfPCell e5 = new PdfPCell(new Paragraph("  " + es2, cellfont));
            PdfPCell e6 = new PdfPCell(new Paragraph("  " + esE, cellfont));
            PdfPCell e7 = new PdfPCell(new Paragraph("  " + elem_total, cellfont));
            PdfPCell e8 = new PdfPCell(new Paragraph(""));
            PdfPCell e9 = new PdfPCell(new Paragraph(""));
            PdfPCell e10 = new PdfPCell(new Paragraph(""));

            PdfPCell sh1 = new PdfPCell(new Paragraph("4", cellfont));
            PdfPCell sh2 = new PdfPCell(new Paragraph("SOCIAL HABITS", cellfont));
            PdfPCell sh3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell sh4 = new PdfPCell(new Paragraph("  " + social1, cellfont));
            PdfPCell sh5 = new PdfPCell(new Paragraph("  " + social2, cellfont));
            PdfPCell sh6 = new PdfPCell(new Paragraph("  " + socialE, cellfont));
            PdfPCell sh7 = new PdfPCell(new Paragraph("  " + social_total, cellfont));
            PdfPCell sh8 = new PdfPCell(new Paragraph(""));
            PdfPCell sh9 = new PdfPCell(new Paragraph(""));
            PdfPCell sh10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell hh1 = new PdfPCell(new Paragraph("5", cellfont));
            PdfPCell hh2 = new PdfPCell(new Paragraph("HEALTH HABITS", cellfont));
            PdfPCell hh3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell hh4 = new PdfPCell(new Paragraph("  " + health1, cellfont));
            PdfPCell hh5 = new PdfPCell(new Paragraph("  " + health2, cellfont));
            PdfPCell hh6 = new PdfPCell(new Paragraph("  " + healthE, cellfont));
            PdfPCell hh7 = new PdfPCell(new Paragraph("  " + health_total, cellfont));
            PdfPCell hh8 = new PdfPCell(new Paragraph(""));
            PdfPCell hh9 = new PdfPCell(new Paragraph(""));
            PdfPCell hh10 = new PdfPCell(new Paragraph(""));

            PdfPCell co1 = new PdfPCell(new Paragraph("6", cellfont));
            PdfPCell co2 = new PdfPCell(new Paragraph("COMPUTER", cellfont));
            PdfPCell co3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell co4 = new PdfPCell(new Paragraph("  " + com1, cellfont));
            PdfPCell co5 = new PdfPCell(new Paragraph("  " + com2, cellfont));
            PdfPCell co6 = new PdfPCell(new Paragraph("  " + comE, cellfont));
            PdfPCell co7 = new PdfPCell(new Paragraph("  " + computer_total, cellfont));
            PdfPCell co8 = new PdfPCell(new Paragraph(""));
            PdfPCell co9 = new PdfPCell(new Paragraph(""));
            PdfPCell co10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell ca1 = new PdfPCell(new Paragraph("7", cellfont));
            PdfPCell ca2 = new PdfPCell(new Paragraph("CULTURAL & CREATIVE ARTS", cellfont));
            PdfPCell ca3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell ca4 = new PdfPCell(new Paragraph("  " + cca1, cellfont));
            PdfPCell ca5 = new PdfPCell(new Paragraph("  " + cca2, cellfont));
            PdfPCell ca6 = new PdfPCell(new Paragraph("  " + ccaE, cellfont));
            PdfPCell ca7 = new PdfPCell(new Paragraph("  " + cca_total, cellfont));
            PdfPCell ca8 = new PdfPCell(new Paragraph(""));
            PdfPCell ca9 = new PdfPCell(new Paragraph(""));
            PdfPCell ca10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell wr1 = new PdfPCell(new Paragraph("8", cellfont));
            PdfPCell wr2 = new PdfPCell(new Paragraph("WRITING", cellfont));
            PdfPCell wr3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell wr4 = new PdfPCell(new Paragraph("  " + writing1, cellfont));
            PdfPCell wr5 = new PdfPCell(new Paragraph("  " + writing2, cellfont));
            PdfPCell wr6 = new PdfPCell(new Paragraph("  " + writingE, cellfont));
            PdfPCell wr7 = new PdfPCell(new Paragraph("  " + writing_total, cellfont));
            PdfPCell wr8 = new PdfPCell(new Paragraph(""));
            PdfPCell wr9 = new PdfPCell(new Paragraph(""));
            PdfPCell wr10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell nr1 = new PdfPCell(new Paragraph("9", cellfont));
            PdfPCell nr2 = new PdfPCell(new Paragraph("NURSERY RHYMES/POEMS", cellfont));
            PdfPCell nr3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell nr4 = new PdfPCell(new Paragraph("  " + rhymes1, cellfont));
            PdfPCell nr5 = new PdfPCell(new Paragraph("  " + rhymes2, cellfont));
            PdfPCell nr6 = new PdfPCell(new Paragraph("  " + rhymesE, cellfont));
            PdfPCell nr7 = new PdfPCell(new Paragraph("  " + rhymes_total, cellfont));
            PdfPCell nr8 = new PdfPCell(new Paragraph(""));
            PdfPCell nr9 = new PdfPCell(new Paragraph(""));
            PdfPCell nr10 = new PdfPCell(new Paragraph(""));

            PdfPCell v1 = new PdfPCell(new Paragraph("10", cellfont));
            PdfPCell v2 = new PdfPCell(new Paragraph("VERBAL REASONING", cellfont));
            PdfPCell v3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell v4 = new PdfPCell(new Paragraph("  " + verbal1, cellfont));
            PdfPCell v5 = new PdfPCell(new Paragraph("  " + verbal2, cellfont));
            PdfPCell v6 = new PdfPCell(new Paragraph("  " + verbalE, cellfont));
            PdfPCell v7 = new PdfPCell(new Paragraph("  " + verbal_total, cellfont));
            PdfPCell v8 = new PdfPCell(new Paragraph(""));
            PdfPCell v9 = new PdfPCell(new Paragraph(""));
            PdfPCell v10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell q1 = new PdfPCell(new Paragraph("11", cellfont));
            PdfPCell q2 = new PdfPCell(new Paragraph("QUANTITATIVE REASONING", cellfont));
            PdfPCell q3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell q4 = new PdfPCell(new Paragraph("  " + quan1, cellfont));
            PdfPCell q5 = new PdfPCell(new Paragraph("  " + quan2, cellfont));
            PdfPCell q6 = new PdfPCell(new Paragraph("  " + quanE, cellfont));
            PdfPCell q7 = new PdfPCell(new Paragraph("  " + quan_total, cellfont));
            PdfPCell q8 = new PdfPCell(new Paragraph(""));
            PdfPCell q9 = new PdfPCell(new Paragraph(""));
            PdfPCell q10 = new PdfPCell(new Paragraph(""));

            PdfPCell m1 = new PdfPCell(new Paragraph("12", cellfont));
            PdfPCell m2 = new PdfPCell(new Paragraph("MORAL INSTRUCTION", cellfont));
            PdfPCell m3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell m4 = new PdfPCell(new Paragraph("  " + moral1, cellfont));
            PdfPCell m5 = new PdfPCell(new Paragraph("  " + moral2, cellfont));
            PdfPCell m6 = new PdfPCell(new Paragraph("  " + moralE, cellfont));
            PdfPCell m7 = new PdfPCell(new Paragraph("  " + moral_total, cellfont));
            PdfPCell m8 = new PdfPCell(new Paragraph(""));
            PdfPCell m9 = new PdfPCell(new Paragraph(""));
            PdfPCell m10 = new PdfPCell(new Paragraph(""));

            PdfPCell t1 = new PdfPCell(new Paragraph(""));
            PdfPCell t2 = new PdfPCell(new Paragraph("TOTAL", cellfont));
            PdfPCell t3 = new PdfPCell(new Paragraph(""));
            PdfPCell t4 = new PdfPCell(new Paragraph(""));
            PdfPCell t5 = new PdfPCell(new Paragraph(""));
            PdfPCell t6 = new PdfPCell(new Paragraph(""));
            PdfPCell t7 = new PdfPCell(new Paragraph("  " + score_total, cellfont));
            PdfPCell t8 = new PdfPCell(new Paragraph(""));
            PdfPCell t9 = new PdfPCell(new Paragraph(""));
            PdfPCell t10 = new PdfPCell(new Paragraph(""));

            //Adding cells to the table.
            table.addCell(c1);
            table.addCell(c2);
            table.addCell(c3);
            table.addCell(c4);
            table.addCell(c5);
            table.addCell(c6);
            table.addCell(c7);
            table.addCell(c8);
            table.addCell(c9);
            table.addCell(c10);

            table.addCell(en1);
            table.addCell(en2);
            table.addCell(en3);
            table.addCell(en4);
            table.addCell(en5);
            table.addCell(en6);
            table.addCell(en7);
            table.addCell(en8);
            table.addCell(en9);
            table.addCell(en10);

            table.addCell(s1);
            table.addCell(s2);
            table.addCell(s3);
            table.addCell(s4);
            table.addCell(s5);
            table.addCell(s6);
            table.addCell(s7);
            table.addCell(s8);
            table.addCell(s9);
            table.addCell(s10);

            table.addCell(e1);
            table.addCell(e2);
            table.addCell(e3);
            table.addCell(e4);
            table.addCell(e5);
            table.addCell(e6);
            table.addCell(e7);
            table.addCell(e8);
            table.addCell(e9);
            table.addCell(e10);

            table.addCell(sh1);
            table.addCell(sh2);
            table.addCell(sh3);
            table.addCell(sh4);
            table.addCell(sh5);
            table.addCell(sh6);
            table.addCell(sh7);
            table.addCell(sh8);
            table.addCell(sh9);
            table.addCell(sh10);

            table.addCell(hh1);
            table.addCell(hh2);
            table.addCell(hh3);
            table.addCell(hh4);
            table.addCell(hh5);
            table.addCell(hh6);
            table.addCell(hh7);
            table.addCell(hh8);
            table.addCell(hh9);
            table.addCell(hh10);

            table.addCell(co1);
            table.addCell(co2);
            table.addCell(co3);
            table.addCell(co4);
            table.addCell(co5);
            table.addCell(co6);
            table.addCell(co7);
            table.addCell(co8);
            table.addCell(co9);
            table.addCell(co10);

            table.addCell(ca1);
            table.addCell(ca2);
            table.addCell(ca3);
            table.addCell(ca4);
            table.addCell(ca5);
            table.addCell(ca6);
            table.addCell(ca7);
            table.addCell(ca8);
            table.addCell(ca9);
            table.addCell(ca10);

            table.addCell(wr1);
            table.addCell(wr2);
            table.addCell(wr3);
            table.addCell(wr4);
            table.addCell(wr5);
            table.addCell(wr6);
            table.addCell(wr7);
            table.addCell(wr8);
            table.addCell(wr9);
            table.addCell(wr10);

            table.addCell(nr1);
            table.addCell(nr2);
            table.addCell(nr3);
            table.addCell(nr4);
            table.addCell(nr5);
            table.addCell(nr6);
            table.addCell(nr7);
            table.addCell(nr8);
            table.addCell(nr9);
            table.addCell(nr10);

            table.addCell(v1);
            table.addCell(v2);
            table.addCell(v3);
            table.addCell(v4);
            table.addCell(v5);
            table.addCell(v6);
            table.addCell(v7);
            table.addCell(v8);
            table.addCell(v9);
            table.addCell(v10);

            table.addCell(q1);
            table.addCell(q2);
            table.addCell(q3);
            table.addCell(q4);
            table.addCell(q5);
            table.addCell(q6);
            table.addCell(q7);
            table.addCell(q8);
            table.addCell(q9);
            table.addCell(q10);

            table.addCell(m1);
            table.addCell(m2);
            table.addCell(m3);
            table.addCell(m4);
            table.addCell(m5);
            table.addCell(m6);
            table.addCell(m7);
            table.addCell(m8);
            table.addCell(m9);
            table.addCell(m10);

            table.addCell(t1);
            table.addCell(t2);
            table.addCell(t3);
            table.addCell(t4);
            table.addCell(t5);
            table.addCell(t6);
            table.addCell(t7);
            table.addCell(t8);
            table.addCell(t9);
            table.addCell(t10);

            document.add(table);

            Paragraph rating = new Paragraph("KEY TO RATING: 5=EXCELLENT   4=GOOD   3=AVERAGE   2=BELLOW AVERAGE   1=POOR", cellfont);
            rating.setAlignment(Element.ALIGN_CENTER);
            document.add(rating);

            //Setting the width and spacing of the table
            PdfPTable table1 = new PdfPTable(12);
            table1.setWidthPercentage(105);
            table1.setSpacingBefore(11f);
            table1.setSpacingAfter(5f);

            //Setting the number of columns
            float[] colWidth1 = {4f, 0.3f, 0.3f, 0.3f, 0.3f, 0.3f, 4f, 0.3f, 0.3f, 0.3f, 0.3f, 0.3f};
            table1.setWidths(colWidth1);

            table1.addCell(new PdfPCell(new Phrase("CHARACTER DEVELOPMENT", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 5", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 4", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 3", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 2", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 1", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("   PRACTICAL SKILL", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 5", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 4", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 3", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 2", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 1", cellfont)));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Education Drama", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Needle Work", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Cookery", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Public Speech", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Sports", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Musical memes", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Oral English", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            document.add(table1);
            /* OSAIGBOVOMWAN VICTORY OSASOGIE */

            Paragraph credit = new Paragraph("", cellfont);
            credit.add("Number of credit(s) ____ Student Average marks: " + average_total + "                                                Class Average: ________");

            Paragraph remark = new Paragraph("", cellfont);
            remark.add("Class Teacher Remarks: ____________________________" + "                                   SCHOOL FEES:");
            remark.setSpacingBefore(3f);

            Paragraph sign = new Paragraph("", cellfont);
            sign.add("Signature: _______________________ Date: ___________" + "                                               Uniform: ________");
            sign.setSpacingBefore(3f);

            Paragraph principal = new Paragraph("", cellfont);
            principal.add("Principal's Remark: ________________________________" + "                                  Next Term Fees: ________");
            principal.setSpacingBefore(3f);

            Paragraph signs = new Paragraph("", cellfont);
            signs.add("Signature: _______________________ Date: ___________" + "                               Outstanding Fees: ________");
            signs.setSpacingBefore(3f);

            Paragraph explain = new Paragraph("", cellfont);
            explain.add("EXPLANATION OF REMARKS " + "                                                                             Other Fees: _____________");
            explain.setSpacingBefore(3f);

            Paragraph fail = new Paragraph("", cellfont);
            fail.add("28 - 39 FAIL         56 - 64 GOOD" + "                                                                    TOTAL: ____________________");
            fail.setSpacingBefore(3f);

            Paragraph pass = new Paragraph("", cellfont);
            pass.add("40 - 45 PASS       65 - 74 VERY GOOD");
            pass.setSpacingBefore(3f);

            Paragraph credits = new Paragraph("", cellfont);
            credits.add("48 - 55 CREDIT   75 - 100 EXCELLENT");
            credits.setSpacingBefore(3f);

            document.add(credit);
            document.add(remark);
            document.add(sign);
            document.add(principal);
            document.add(signs);
            document.add(explain);
            document.add(fail);
            document.add(pass);
            document.add(credits);
            JOptionPane.showMessageDialog(this, "Result saved");
            document.close();
            pdfWriter.close();

        } catch (DocumentException | FileNotFoundException e) {
            System.out.println(e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtArts;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtComputer;
    private javax.swing.JTextField txtElem;
    private javax.swing.JTextField txtEnglish;
    public static javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtHealth;
    private javax.swing.JTextField txtMoral;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtQuan;
    private javax.swing.JTextField txtRhymes;
    private javax.swing.JTextField txtSocial;
    private javax.swing.JTextField txtSound;
    public static javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtTotalScore;
    private javax.swing.JTextArea txtTranscript;
    private javax.swing.JTextField txtVerbal;
    private javax.swing.JTextField txtWriting;
    // End of variables declaration//GEN-END:variables
}
