/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgtsystem.view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import schoolmgtsystem.model.dbhelper.DBHandler;

/**
 *
 * @author Thomas
 */
public class StudentResult_Primary extends javax.swing.JFrame {

    DBHandler handler;

    /**
     * Creates new form ResultPrimary
     */
    public StudentResult_Primary() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtTotalScore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPHE = new javax.swing.JTextField();
        txtBT = new javax.swing.JTextField();
        txtBS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCRS = new javax.swing.JTextField();
        txtEnglish = new javax.swing.JTextField();
        txtMaths = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtICT = new javax.swing.JTextField();
        txtVerbal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSocial = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCivic = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtSecurity = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtAgric = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtHome = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtEdo = new javax.swing.JTextField();
        txtQuan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClass = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTranscript = new javax.swing.JTextArea();
        btnRanking = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "PRIMARY SCHOOL RESULT RECORDS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 107, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 107, -1));

        txtFullName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 300, -1));

        txtTotalScore.setEditable(false);
        txtTotalScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotalScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalScoreActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total Score");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 107, -1));

        txtAverage.setEditable(false);
        txtAverage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAverage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Average");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 107, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Basic Technology");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Physical Health");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 150, -1));

        txtPHE.setEditable(false);
        txtPHE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPHE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 90, -1));

        txtBT.setEditable(false);
        txtBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 90, -1));

        txtBS.setEditable(false);
        txtBS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Basic Science");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("C R S");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 107, -1));

        txtCRS.setEditable(false);
        txtCRS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCRS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 90, -1));

        txtEnglish.setEditable(false);
        txtEnglish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEnglish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 90, -1));

        txtMaths.setEditable(false);
        txtMaths.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMaths.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 90, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Maths");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 66, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("English");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 107, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 326, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Position");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 107, -1));

        txtPosition.setEditable(false);
        txtPosition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Information & Communication");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 180, -1));

        txtICT.setEditable(false);
        txtICT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtICT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtICT, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 90, -1));

        txtVerbal.setEditable(false);
        txtVerbal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtVerbal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVerbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerbalActionPerformed(evt);
            }
        });
        jPanel1.add(txtVerbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Verbal Reasoning");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 170, -1));

        txtSocial.setEditable(false);
        txtSocial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSocial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 90, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Social Studies");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 170, -1));

        txtStudentID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtStudentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Civic Education");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 150, -1));

        txtCivic.setEditable(false);
        txtCivic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCivic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCivic, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 90, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Security Education");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 180, -1));

        txtSecurity.setEditable(false);
        txtSecurity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSecurity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 90, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Agriculture");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        txtAgric.setEditable(false);
        txtAgric.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAgric.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAgric, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 90, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Home Economics");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 160, -1));

        txtHome.setEditable(false);
        txtHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtHome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Edo Language");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Quantitative R.");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 140, -1));

        txtEdo.setEditable(false);
        txtEdo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEdo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtEdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 90, -1));

        txtQuan.setEditable(false);
        txtQuan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQuan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Class");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 60, -1));

        txtClass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtClass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 100, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 810, 590));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "Result Printout", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        txtTranscript.setEditable(false);
        txtTranscript.setColumns(20);
        txtTranscript.setRows(5);
        jScrollPane1.setViewportView(txtTranscript);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 380, 590));

        btnRanking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRanking.setText("Ranking");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        jPanel4.add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, -1, -1));

        btnTranscript.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });
        jPanel4.add(btnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, -1));

        btnGenerate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel4.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, -1, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 610, -1, -1));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmgtsystem/IconImages/icons8_Left_30px_1.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalScoreActionPerformed

    private void txtVerbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerbalActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        double[] R = new double[18];

        R[0] = Double.parseDouble(txtMaths.getText());
        R[1] = Double.parseDouble(txtEnglish.getText());
        R[2] = Double.parseDouble(txtCRS.getText());
        R[3] = Double.parseDouble(txtBS.getText());
        R[4] = Double.parseDouble(txtBT.getText());
        R[5] = Double.parseDouble(txtPHE.getText());
        R[6] = Double.parseDouble(txtICT.getText());
        R[7] = Double.parseDouble(txtVerbal.getText());
        R[8] = Double.parseDouble(txtSocial.getText());
        R[9] = Double.parseDouble(txtCivic.getText());
        R[10] = Double.parseDouble(txtSecurity.getText());
        R[11] = Double.parseDouble(txtHome.getText());
        R[12] = Double.parseDouble(txtAgric.getText());
        R[13] = Double.parseDouble(txtEdo.getText());
        R[14] = Double.parseDouble(txtQuan.getText());

        R[15] = (R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7] + R[8] + R[9] + R[10] + R[11] + R[12] + R[13] + R[14]) / 15;
        //R[9] = (R[0] + R[1] + R[2] + R[3] + R[5] + R[6] + R[7])/7;
        R[16] = R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7] + R[8] + R[9] + R[10] + R[11] + R[12] + R[13] + R[14];

        String Average = String.format("%.0f", R[15]);
        txtAverage.setText(Average);

        String TotalScore = String.format("%.0f", R[16]);
        txtTotalScore.setText(TotalScore);

        if (R[16] >= 100) {
            txtPosition.setText("1st");
        } else if (R[16] >= 90) {
            txtPosition.setText("2nd");
        } else if (R[16] >= 80) {
            txtPosition.setText("3rd");
        } else if (R[16] >= 70) {
            txtPosition.setText("4th");
        } else if (R[16] >= 60) {
            txtPosition.setText("5th");
        } else if (R[16] >= 50) {
            txtPosition.setText("Average");
        } else if (R[16] >= 40) {
            txtPosition.setText("Fail");
        }
        //else if (R[10] >= 100){
        //txtRanking.setText("Poor");
        //}
        //else if (R[10] >= 50){
        // txtRanking.setText("Fail");
        //}

        //        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //        model.addRow(new Object[]{
        //            txtStudentID.getText(),
        //            txtFirstName.getText(),
        //            txtSurname.getText(),
        //            txtCourseCode.getSelectedItem(),
        //            txtMaths.getText(),
        //            txtEnglish.getText(),
        //            txtLit.getText(),
        //            txtBS.getText(),
        //            txtBT.getText(),
        //            txtPHE.getText(),
        //            txtICT.getText(),
        //            txtCRS.getText(),
        //            txtSocial.getText(),
        //            txtTotalScore.getText(),
        //            txtAverage.getText(),
        //            txtPosition.getText()
        //        });
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
        txtTranscript.append("BRIGHT STARS SCHOOL"
                + "\n\tStudent Result"
                + "\n_____________________________________"
                + "\nStudent ID:\t\t" + txtStudentID.getText()
                + "\n_____________________________________"
                //                + "\nFirst Name:\t\t" + txtFirstName.getText()
                //                + "\n_____________________________________"
                //                + "\nSurname:\t\t" + txtSurname.getText()
                //                + "\n_____________________________________"
                //            + "\nCourse Code:\t\t" + txtCourseCode.getSelectedItem()
                //            + "\n_____________________________________"
                + "\nMaths:\t\t" + txtMaths.getText()
                + "\n_____________________________________"
                + "\nEnglish:\t\t" + txtEnglish.getText()
                + "\n_____________________________________"
                + "\nC R S:\t\t" + txtCRS.getText()
                + "\n_____________________________________"
                + "\nBasic Science:\t\t" + txtBS.getText()
                + "\n_____________________________________"
                + "\nBasic Technology:\t" + txtBT.getText()
                + "\n_____________________________________"
                + "\nPhysical Education:\t" + txtPHE.getText()
                + "\n_____________________________________"
                + "\nInformation Tech.:\t" + txtICT.getText()
                + "\n_____________________________________"
                + "\nVerbal:\t\t" + txtVerbal.getText()
                + "\n_____________________________________"
                + "\nSocial Studies:\t\t" + txtSocial.getText()
                + "\n_____________________________________"
                + "\nCivic Education:\t\t" + txtCivic.getText()
                + "\n_____________________________________"
                + "\nSecurity Education:\t" + txtSecurity.getText()
                + "\n_____________________________________"
                + "\nHome Economics:\t" + txtHome.getText()
                + "\n_____________________________________"
                + "\nAgriculture:\t\t" + txtAgric.getText()
                + "\n_____________________________________"
                + "\nEdo Language:\t\t" + txtEdo.getText()
                + "\n_____________________________________"
                + "\nQuantitative R..:\t" + txtQuan.getText()
                + "\n_____________________________________"
                + "\nTotal Score:\t\t" + txtTotalScore.getText()
                + "\n_____________________________________"
                + "\nAverage:\t\t" + txtAverage.getText()
                + "\n_____________________________________"
                + "\nPosition:\t\t" + txtPosition.getText()
                + "\n_____________________________________"
        );


    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:

        handler = new DBHandler();

        String str = "select * from prime where StudentID = ?";
        try {
            PreparedStatement preparedStatement = handler.getdbConnection().prepareStatement(str);
            preparedStatement.setString(1, txtStudentID.getText());

            ResultSet rs = preparedStatement.executeQuery();

            while (rs.next()) {

                txtStudentID.setText(rs.getString("StudentID"));
                txtMaths.setText(rs.getString("Maths_Total"));
                txtEnglish.setText(rs.getString("English_Total"));
                txtCRS.setText(rs.getString("CRS_Total"));
                txtBS.setText(rs.getString("BS_Total"));
                txtBT.setText(rs.getString("BT_Total"));
                txtPHE.setText(rs.getString("PHE_Total"));
                txtICT.setText(rs.getString("ICT_Total"));
                txtVerbal.setText(rs.getString("Verbal_Total"));
                txtSocial.setText(rs.getString("Social_Total"));
                txtCivic.setText(rs.getString("Civic_Total"));
                txtSecurity.setText(rs.getString("Security_Total"));
                txtHome.setText(rs.getString("Home_Total"));
                txtAgric.setText(rs.getString("Agric_Total"));
                txtEdo.setText(rs.getString("Edo_Total"));
                txtQuan.setText(rs.getString("Quan_Total"));

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ResultSSS.class.getName()).log(Level.SEVERE, null, ex);
        }

        String ID = txtStudentID.getText();
        String getName_Class = "SELECT * FROM student_details WHERE StudentID = ?";
        String validate = "SELECT StudentID FROM prime WHERE StudentID = ?";

        try {
            handler = new DBHandler();
            ResultSet rs = null;
            ResultSet rs1 = null;
            PreparedStatement pst = handler.getdbConnection().prepareStatement(getName_Class);
            PreparedStatement pst1 = handler.getdbConnection().prepareStatement(validate);

            pst.setString(1, txtStudentID.getText());
            pst1.setString(1, txtStudentID.getText());

            rs = pst.executeQuery();
            rs1 = pst1.executeQuery();

            if (rs.next() && rs1.next()) {

                getClassID = rs.getString("StudentID");
                getAdmClass = rs.getString("AdmissionClass");
                getSname = rs.getString("StudentName");
                getSchoolID = rs1.getString("StudentID");

                System.out.println(getClassID + ", " + getSchoolID);

                if (getClassID.equals(getSchoolID)) {

                    txtClass.setText(getAdmClass);
                    txtFullName.setText(getSname);

                }

            } else {
                System.out.println("Not Valid");
                JOptionPane.showMessageDialog(this, "No Student ID as " + ID + " in Primary");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        JTextField temp = null;
        for (Component C : jPanel1.getComponents()) {
            if (C.getClass().toString().contains("javax.swing.JTextField")) {

                temp = (JTextField) C;
                temp.setText(null);

                JTextArea tem = null;
                for (Component A : jPanel1.getComponents()) {
                    if (A.getClass().toString().contains("javax.swing.JTextArea")) {

                        tem = (JTextArea) A;
                        tem.setText(null);
                    }
                    txtTranscript.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:

        int sel = JOptionPane.showConfirmDialog(this, "Do you want to print Result?");
        if (sel == 0) {
            try {
                printResult();
            } catch (IOException ex) {
                Logger.getLogger(ResultNursery.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (sel == 1) {
            this.show();
        }
        if (sel == 2) {
            this.show();
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResult_Primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentResult_Primary().setVisible(true);
        });
    }

    public void printResult() throws IOException {

        //PreparedStatement to get the 1st and 2nd Test score
        String str = "select * from prime where StudentID = ?";

        handler = new DBHandler();

        String english1 = null, english2 = null, englishE = null, maths1 = null, maths2 = null, mathsE = null, crs1 = null,
                crs2 = null, crsE = null, civic1 = null, civic2 = null, civicE = null, social1 = null, social2 = null, socialE = null,
                security1 = null, security2 = null, securityE = null, bs1 = null, bs2 = null, bsE = null, bt1 = null, bt2 = null, btE = null,
                phe1 = null, phe2 = null, pheE = null, ict1 = null, ict2 = null, ictE = null, home1 = null, home2 = null,
                homeE = null, agric1 = null, agric2 = null, agricE = null, edo1 = null, edo2 = null, edoE = null, verbal1 = null,
                verbal2 = null, verbalE = null, quan1 = null, quan2 = null, quanE = null;

        try {
            PreparedStatement pst = handler.getdbConnection().prepareStatement(str);

//             Statement pst = handler.getdbConnection().createStatement();
            pst.setString(1, txtStudentID.getText());

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                txtStudentID.setText(rs.getString("StudentID"));
                english1 = rs.getString("English1");
                english2 = rs.getString("English2");
                englishE = rs.getString("English_Exam");
                maths1 = rs.getString("Maths1");
                maths2 = rs.getString("Maths2");
                mathsE = rs.getString("Maths_Exam");
                crs1 = rs.getString("CRS1");
                crs2 = rs.getString("CRS2");
                crsE = rs.getString("CRS_Exam");
                civic1 = rs.getString("Civic1");
                civic2 = rs.getString("Civic2");
                civicE = rs.getString("Civic_Exam");
                social1 = rs.getString("Social1");
                social2 = rs.getString("Social2");
                socialE = rs.getString("Social_Exam");
                security1 = rs.getString("Security1");
                security2 = rs.getString("Security2");
                securityE = rs.getString("Security_Exam");
                bs1 = rs.getString("BS1");
                bs2 = rs.getString("BS2");
                bsE = rs.getString("BS_Exam");
                bt1 = rs.getString("BT1");
                bt2 = rs.getString("BT2");
                btE = rs.getString("BT_Exam");
                phe1 = rs.getString("PHE1");
                phe2 = rs.getString("PHE2");
                pheE = rs.getString("PHE_Exam");
                ict1 = rs.getString("ICT1");
                ict2 = rs.getString("ICT2");
                ictE = rs.getString("ICT_Exam");
                home1 = rs.getString("Home1");
                home2 = rs.getString("Home2");
                homeE = rs.getString("Home_Exam");
                agric1 = rs.getString("Agric1");
                agric2 = rs.getString("Agric2");
                agricE = rs.getString("Agric_Exam");
                edo1 = rs.getString("Edo1");
                edo2 = rs.getString("Edo2");
                edoE = rs.getString("Edo_Exam");
                verbal1 = rs.getString("Verbal1");
                verbal2 = rs.getString("Verbal2");
                verbalE = rs.getString("Verbal_Exam");
                quan1 = rs.getString("Quan1");
                quan2 = rs.getString("Quan2");
                quanE = rs.getString("Quan_Exam");

            }

            System.out.println("1st Test " + english1);
            System.out.println("2st Test " + english2);
            System.out.println("Exam " + englishE);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ResultNursery.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Creating a file dialog with file chooser
        //Prints out file in PDF format
        JFileChooser chooser = new JFileChooser();
        chooser.showSaveDialog(this);
        chooser.getSelectedFile();

        File file = chooser.getSelectedFile();

        Document document = new Document();
        Font font = new Font();

        try {

            String english_total = txtEnglish.getText();
            String maths_total = txtMaths.getText();
            String crs_total = txtCRS.getText();
            String civic_total = txtCivic.getText();
            String social_total = txtSocial.getText();
            String security_total = txtSecurity.getText();
            String bs_total = txtBS.getText();
            String bt_total = txtBT.getText();
            String phe_total = txtPHE.getText();
            String ict_total = txtICT.getText();
            String home_total = txtHome.getText();
            String agric_total = txtAgric.getText();
            String edo_total = txtEdo.getText();
            String verbal_total = txtVerbal.getText();
            String quan_total = txtQuan.getText();
            String score_total = txtTotalScore.getText();
            String average_total = txtAverage.getText();
            String position_total = txtPosition.getText();

            System.out.println("English Total " + english_total);

            PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(file));
            document.open();

//            document.add(new Paragraph(content));
//            document.add(new Paragraph(title));
            Image image = Image.getInstance("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\SchoolMgtSystem\\Bright_Stars.png");
            image.setAbsolutePosition(70, 738);

            Font infofont = new Font(Font.FontFamily.TIMES_ROMAN, 11.5f, Font.BOLD);
            Font detailsfont = new Font(Font.FontFamily.HELVETICA, 11f, Font.NORMAL);
            Font namefont = new Font(Font.FontFamily.TIMES_ROMAN, 12.5f, Font.BOLD);
            Font motofont = new Font(Font.FontFamily.TIMES_ROMAN, 9, Font.BOLD);

            Paragraph ti = new Paragraph("", namefont);
            ti.add("BRIGHT STARS PRIMARY SCHOOL");
            ti.setAlignment(Element.ALIGN_CENTER);
//            font = ti.getFont();
//            font.setSize(12.5f);

            Paragraph sl = new Paragraph("", motofont);
            sl.add("(NURSERY, PRIMARY & SECONDARY)");
            sl.setAlignment(Element.ALIGN_CENTER);
            font = sl.getFont();
            font.setSize(10);
            sl.setSpacingBefore(0f);
            sl.setSpacingAfter(0f);

            Paragraph sti = new Paragraph("", infofont);
            sti.add("Omorodion Osaretin Str, Off Okuwague\nEvbabogun Road, Off Sapele Road, Benin City");
            sti.setAlignment(Element.ALIGN_CENTER);
            sti.setSpacingBefore(0f);
            sti.setSpacingAfter(0f);

            Paragraph tele = new Paragraph("", infofont);
            tele.add("TEL: 07067183000" + " \tEmail: informbrightstars@yahoo.com");
            tele.setAlignment(Element.ALIGN_CENTER);
            tele.setSpacingBefore(0f);
            tele.setSpacingAfter(0f);

            Paragraph mot = new Paragraph("", infofont);
            mot.add("MOTTO: Knowledge for Excellence");
            mot.setAlignment(Element.ALIGN_CENTER);
            mot.setSpacingBefore(0f);
            mot.setSpacingAfter(0f);

            Paragraph name = new Paragraph("", detailsfont);
            name.setAlignment(Element.ALIGN_CENTER);
            name.add("Name of pupil: " + txtFullName.getText()
                    + "   Sex: ____" + "   Age: ____" + "   Adm NO: " + txtStudentID.getText());
            name.setSpacingBefore(8f);

            Paragraph house = new Paragraph("", detailsfont);
            house.setAlignment(Element.ALIGN_CENTER);
            house.add("Assessment for: __________"
                    + " Term: ________" + " Class: __________" + " NO In class: ______" /*+ " Position: _______"*/);
            house.setSpacingBefore(5f);
//            house.setSpacingAfter(10f);

            Paragraph pos = new Paragraph("", detailsfont);
            pos.setAlignment(Element.ALIGN_CENTER);
            pos.add("Position: " + position_total + " School House: ________" + " 20___ / 20___ session  Attendance ____ Out of ____");
            pos.setSpacingBefore(5f);
//            pos.setSpacingAfter(10f);

            Paragraph res = new Paragraph("", detailsfont);
            res.setAlignment(Element.ALIGN_CENTER);
            res.add("Resumption: _________________");
            res.setSpacingBefore(5f);
            res.setSpacingAfter(8f);

            //Adding to the Document
            document.add(image);
            document.add(ti);
            document.add(sl);
            document.add(sti);
            document.add(tele);
            document.add(mot);
            document.add(name);
            document.add(house);
            document.add(pos);
            document.add(res);

//            document.add(new Paragraph(subTitle));
//            document.add(new Paragraph("Student ID: " + txtStudentID.getText()));
//            document.add(new Paragraph("Full Name: " + txtFullName.getText()));
//            document.add(new Paragraph("Surname: " + txtSurname.getText()));
//            document.add(new Paragraph("Course Code: " + txtCourseCode.getSelectedItem()));
//            document.add(new Paragraph("DETAILED RESULT"));
            PdfPTable table = new PdfPTable(10);
            table.setWidthPercentage(105);
            table.setSpacingBefore(8f);
            table.setSpacingAfter(8f);

            float[] colWidth = {0.3f, 3f, 0.5f, 0.5f, 0.5f, 0.6f, 0.6f, 0.5f, 0.6f, 0.5f};
            table.setWidths(colWidth);

//            DEFINING FONT SIZES FOR THE TABLE HEADER ANND TABLE CELLS
            Font headerfont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);
            Font cellfont = new Font(Font.FontFamily.HELVETICA, 10.8f, Font.NORMAL);

            //adding values to the cells
            PdfPCell c1 = new PdfPCell(new Paragraph("", headerfont));
            PdfPCell c2 = new PdfPCell(new Paragraph("", headerfont));
            PdfPCell c3 = new PdfPCell(new Paragraph(" MAX\n 100", headerfont));
            PdfPCell c4 = new PdfPCell(new Paragraph(" 1ST TEST\n  20", headerfont));
            PdfPCell c5 = new PdfPCell(new Paragraph(" 2ND TEST\n  20", headerfont));
            PdfPCell c6 = new PdfPCell(new Paragraph("EXAM\n  60", headerfont));
            PdfPCell c7 = new PdfPCell(new Paragraph("TOTAL\n  100", headerfont));
            PdfPCell c8 = new PdfPCell(new Paragraph("POSITION", headerfont));
            PdfPCell c9 = new PdfPCell(new Paragraph("REMARKS", headerfont));
            PdfPCell c10 = new PdfPCell(new Paragraph("SIGN", headerfont));

            PdfPCell en1 = new PdfPCell(new Paragraph("1", cellfont));
            PdfPCell en2 = new PdfPCell(new Paragraph("ENGLISH STUDIES", cellfont));
            PdfPCell en3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell en4 = new PdfPCell(new Paragraph("  " + english1, cellfont));
            PdfPCell en5 = new PdfPCell(new Paragraph("  " + english2, cellfont));
            PdfPCell en6 = new PdfPCell(new Paragraph("  " + englishE, cellfont));
            PdfPCell en7 = new PdfPCell(new Paragraph("  " + english_total, cellfont));
            PdfPCell en8 = new PdfPCell(new Paragraph(""));
            PdfPCell en9 = new PdfPCell(new Paragraph(""));
            PdfPCell en10 = new PdfPCell(new Paragraph(""));

            PdfPCell s1 = new PdfPCell(new Paragraph("2", cellfont));
            PdfPCell s2 = new PdfPCell(new Paragraph("MATHEMATICS", cellfont));
            PdfPCell s3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell s4 = new PdfPCell(new Paragraph("  " + maths1, cellfont));
            PdfPCell s5 = new PdfPCell(new Paragraph("  " + maths2, cellfont));
            PdfPCell s6 = new PdfPCell(new Paragraph("  " + mathsE, cellfont));
            PdfPCell s7 = new PdfPCell(new Paragraph("  " + maths_total, cellfont));
            PdfPCell s8 = new PdfPCell(new Paragraph(""));
            PdfPCell s9 = new PdfPCell(new Paragraph(""));
            PdfPCell s10 = new PdfPCell(new Paragraph(""));

            PdfPCell e1 = new PdfPCell(new Paragraph("3", cellfont));
            PdfPCell e2 = new PdfPCell(new Paragraph("C R S", cellfont));
            PdfPCell e3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell e4 = new PdfPCell(new Paragraph("  " + crs1, cellfont));
            PdfPCell e5 = new PdfPCell(new Paragraph("  " + crs2, cellfont));
            PdfPCell e6 = new PdfPCell(new Paragraph("  " + crsE, cellfont));
            PdfPCell e7 = new PdfPCell(new Paragraph("  " + crs_total, cellfont));
            PdfPCell e8 = new PdfPCell(new Paragraph(""));
            PdfPCell e9 = new PdfPCell(new Paragraph(""));
            PdfPCell e10 = new PdfPCell(new Paragraph(""));

            PdfPCell sh1 = new PdfPCell(new Paragraph("4", cellfont));
            PdfPCell sh2 = new PdfPCell(new Paragraph("CIVIC EDUCATION", cellfont));
            PdfPCell sh3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell sh4 = new PdfPCell(new Paragraph("  " + civic1, cellfont));
            PdfPCell sh5 = new PdfPCell(new Paragraph("  " + civic2, cellfont));
            PdfPCell sh6 = new PdfPCell(new Paragraph("  " + civicE, cellfont));
            PdfPCell sh7 = new PdfPCell(new Paragraph("  " + civic_total, cellfont));
            PdfPCell sh8 = new PdfPCell(new Paragraph(""));
            PdfPCell sh9 = new PdfPCell(new Paragraph(""));
            PdfPCell sh10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell hh1 = new PdfPCell(new Paragraph("5", cellfont));
            PdfPCell hh2 = new PdfPCell(new Paragraph("SOCIAL STUDIES", cellfont));
            PdfPCell hh3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell hh4 = new PdfPCell(new Paragraph("  " + social1, cellfont));
            PdfPCell hh5 = new PdfPCell(new Paragraph("  " + social2, cellfont));
            PdfPCell hh6 = new PdfPCell(new Paragraph("  " + socialE, cellfont));
            PdfPCell hh7 = new PdfPCell(new Paragraph("  " + social_total, cellfont));
            PdfPCell hh8 = new PdfPCell(new Paragraph(""));
            PdfPCell hh9 = new PdfPCell(new Paragraph(""));
            PdfPCell hh10 = new PdfPCell(new Paragraph(""));

            PdfPCell co1 = new PdfPCell(new Paragraph("6", cellfont));
            PdfPCell co2 = new PdfPCell(new Paragraph("SECURITY EDUCATION", cellfont));
            PdfPCell co3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell co4 = new PdfPCell(new Paragraph("  " + security1, cellfont));
            PdfPCell co5 = new PdfPCell(new Paragraph("  " + security2, cellfont));
            PdfPCell co6 = new PdfPCell(new Paragraph("  " + securityE, cellfont));
            PdfPCell co7 = new PdfPCell(new Paragraph("  " + security_total, cellfont));
            PdfPCell co8 = new PdfPCell(new Paragraph(""));
            PdfPCell co9 = new PdfPCell(new Paragraph(""));
            PdfPCell co10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell ca1 = new PdfPCell(new Paragraph("7", cellfont));
            PdfPCell ca2 = new PdfPCell(new Paragraph("BASIC SCIENCE", cellfont));
            PdfPCell ca3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell ca4 = new PdfPCell(new Paragraph("  " + bs1, cellfont));
            PdfPCell ca5 = new PdfPCell(new Paragraph("  " + bs2, cellfont));
            PdfPCell ca6 = new PdfPCell(new Paragraph("  " + bsE, cellfont));
            PdfPCell ca7 = new PdfPCell(new Paragraph("  " + bs_total, cellfont));
            PdfPCell ca8 = new PdfPCell(new Paragraph(""));
            PdfPCell ca9 = new PdfPCell(new Paragraph(""));
            PdfPCell ca10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell wr1 = new PdfPCell(new Paragraph("8", cellfont));
            PdfPCell wr2 = new PdfPCell(new Paragraph("BASIC TECHNOLOGY", cellfont));
            PdfPCell wr3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell wr4 = new PdfPCell(new Paragraph("  " + bt1, cellfont));
            PdfPCell wr5 = new PdfPCell(new Paragraph("  " + bt2, cellfont));
            PdfPCell wr6 = new PdfPCell(new Paragraph("  " + btE, cellfont));
            PdfPCell wr7 = new PdfPCell(new Paragraph("  " + bt_total, cellfont));
            PdfPCell wr8 = new PdfPCell(new Paragraph(""));
            PdfPCell wr9 = new PdfPCell(new Paragraph(""));
            PdfPCell wr10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell nr1 = new PdfPCell(new Paragraph("9", cellfont));
            PdfPCell nr2 = new PdfPCell(new Paragraph("PHYSICAL & HEALTH EDUCATION", cellfont));
            PdfPCell nr3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell nr4 = new PdfPCell(new Paragraph("  " + phe1, cellfont));
            PdfPCell nr5 = new PdfPCell(new Paragraph("  " + phe2, cellfont));
            PdfPCell nr6 = new PdfPCell(new Paragraph("  " + pheE, cellfont));
            PdfPCell nr7 = new PdfPCell(new Paragraph("  " + phe_total, cellfont));
            PdfPCell nr8 = new PdfPCell(new Paragraph(""));
            PdfPCell nr9 = new PdfPCell(new Paragraph(""));
            PdfPCell nr10 = new PdfPCell(new Paragraph(""));

            PdfPCell v1 = new PdfPCell(new Paragraph("10", cellfont));
            PdfPCell v2 = new PdfPCell(new Paragraph("INFORMATION TECHNOLOGY", cellfont));
            PdfPCell v3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell v4 = new PdfPCell(new Paragraph("  " + ict1, cellfont));
            PdfPCell v5 = new PdfPCell(new Paragraph("  " + ict2, cellfont));
            PdfPCell v6 = new PdfPCell(new Paragraph("  " + ictE, cellfont));
            PdfPCell v7 = new PdfPCell(new Paragraph("  " + ict_total, cellfont));
            PdfPCell v8 = new PdfPCell(new Paragraph(""));
            PdfPCell v9 = new PdfPCell(new Paragraph(""));
            PdfPCell v10 = new PdfPCell(new Paragraph(""));
//
            PdfPCell q1 = new PdfPCell(new Paragraph("11", cellfont));
            PdfPCell q2 = new PdfPCell(new Paragraph("HOME ECONOMICS", cellfont));
            PdfPCell q3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell q4 = new PdfPCell(new Paragraph("  " + home1, cellfont));
            PdfPCell q5 = new PdfPCell(new Paragraph("  " + home2, cellfont));
            PdfPCell q6 = new PdfPCell(new Paragraph("  " + homeE, cellfont));
            PdfPCell q7 = new PdfPCell(new Paragraph("  " + home_total, cellfont));
            PdfPCell q8 = new PdfPCell(new Paragraph(""));
            PdfPCell q9 = new PdfPCell(new Paragraph(""));
            PdfPCell q10 = new PdfPCell(new Paragraph(""));

            PdfPCell m1 = new PdfPCell(new Paragraph("12", cellfont));
            PdfPCell m2 = new PdfPCell(new Paragraph("AGRICULTURAL SCIENCE", cellfont));
            PdfPCell m3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell m4 = new PdfPCell(new Paragraph("  " + agric1, cellfont));
            PdfPCell m5 = new PdfPCell(new Paragraph("  " + agric2, cellfont));
            PdfPCell m6 = new PdfPCell(new Paragraph("  " + agricE, cellfont));
            PdfPCell m7 = new PdfPCell(new Paragraph("  " + agric_total, cellfont));
            PdfPCell m8 = new PdfPCell(new Paragraph(""));
            PdfPCell m9 = new PdfPCell(new Paragraph(""));
            PdfPCell m10 = new PdfPCell(new Paragraph(""));

            PdfPCell ed1 = new PdfPCell(new Paragraph("13", cellfont));
            PdfPCell ed2 = new PdfPCell(new Paragraph("EDO LANGUAGE", cellfont));
            PdfPCell ed3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell ed4 = new PdfPCell(new Paragraph("  " + edo1, cellfont));
            PdfPCell ed5 = new PdfPCell(new Paragraph("  " + edo2, cellfont));
            PdfPCell ed6 = new PdfPCell(new Paragraph("  " + edoE, cellfont));
            PdfPCell ed7 = new PdfPCell(new Paragraph("  " + edo_total, cellfont));
            PdfPCell ed8 = new PdfPCell(new Paragraph(""));
            PdfPCell ed9 = new PdfPCell(new Paragraph(""));
            PdfPCell ed10 = new PdfPCell(new Paragraph(""));

            PdfPCell ve1 = new PdfPCell(new Paragraph("14", cellfont));
            PdfPCell ve2 = new PdfPCell(new Paragraph("VERBAL REASONING", cellfont));
            PdfPCell ve3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell ve4 = new PdfPCell(new Paragraph("  " + verbal1, cellfont));
            PdfPCell ve5 = new PdfPCell(new Paragraph("  " + verbal2, cellfont));
            PdfPCell ve6 = new PdfPCell(new Paragraph("  " + verbalE, cellfont));
            PdfPCell ve7 = new PdfPCell(new Paragraph("  " + verbal_total, cellfont));
            PdfPCell ve8 = new PdfPCell(new Paragraph(""));
            PdfPCell ve9 = new PdfPCell(new Paragraph(""));
            PdfPCell ve10 = new PdfPCell(new Paragraph(""));

            PdfPCell qu1 = new PdfPCell(new Paragraph("15", cellfont));
            PdfPCell qu2 = new PdfPCell(new Paragraph("QUANTITATIVE REASONING", cellfont));
            PdfPCell qu3 = new PdfPCell(new Paragraph(" 100", cellfont));
            PdfPCell qu4 = new PdfPCell(new Paragraph("  " + quan1, cellfont));
            PdfPCell qu5 = new PdfPCell(new Paragraph("  " + quan2, cellfont));
            PdfPCell qu6 = new PdfPCell(new Paragraph("  " + quanE, cellfont));
            PdfPCell qu7 = new PdfPCell(new Paragraph("  " + quan_total, cellfont));
            PdfPCell qu8 = new PdfPCell(new Paragraph(""));
            PdfPCell qu9 = new PdfPCell(new Paragraph(""));
            PdfPCell qu10 = new PdfPCell(new Paragraph(""));

            PdfPCell t1 = new PdfPCell(new Paragraph(""));
            PdfPCell t2 = new PdfPCell(new Paragraph("TOTAL", cellfont));
            PdfPCell t3 = new PdfPCell(new Paragraph(""));
            PdfPCell t4 = new PdfPCell(new Paragraph(""));
            PdfPCell t5 = new PdfPCell(new Paragraph(""));
            PdfPCell t6 = new PdfPCell(new Paragraph(""));
            PdfPCell t7 = new PdfPCell(new Paragraph("  " + score_total, cellfont));
            PdfPCell t8 = new PdfPCell(new Paragraph(""));
            PdfPCell t9 = new PdfPCell(new Paragraph(""));
            PdfPCell t10 = new PdfPCell(new Paragraph(""));

            //Adding cells to the table.
            table.addCell(c1);
            table.addCell(c2);
            table.addCell(c3);
            table.addCell(c4);
            table.addCell(c5);
            table.addCell(c6);
            table.addCell(c7);
            table.addCell(c8);
            table.addCell(c9);
            table.addCell(c10);

            table.addCell(en1);
            table.addCell(en2);
            table.addCell(en3);
            table.addCell(en4);
            table.addCell(en5);
            table.addCell(en6);
            table.addCell(en7);
            table.addCell(en8);
            table.addCell(en9);
            table.addCell(en10);

            table.addCell(s1);
            table.addCell(s2);
            table.addCell(s3);
            table.addCell(s4);
            table.addCell(s5);
            table.addCell(s6);
            table.addCell(s7);
            table.addCell(s8);
            table.addCell(s9);
            table.addCell(s10);

            table.addCell(e1);
            table.addCell(e2);
            table.addCell(e3);
            table.addCell(e4);
            table.addCell(e5);
            table.addCell(e6);
            table.addCell(e7);
            table.addCell(e8);
            table.addCell(e9);
            table.addCell(e10);

            table.addCell(sh1);
            table.addCell(sh2);
            table.addCell(sh3);
            table.addCell(sh4);
            table.addCell(sh5);
            table.addCell(sh6);
            table.addCell(sh7);
            table.addCell(sh8);
            table.addCell(sh9);
            table.addCell(sh10);

            table.addCell(hh1);
            table.addCell(hh2);
            table.addCell(hh3);
            table.addCell(hh4);
            table.addCell(hh5);
            table.addCell(hh6);
            table.addCell(hh7);
            table.addCell(hh8);
            table.addCell(hh9);
            table.addCell(hh10);

            table.addCell(co1);
            table.addCell(co2);
            table.addCell(co3);
            table.addCell(co4);
            table.addCell(co5);
            table.addCell(co6);
            table.addCell(co7);
            table.addCell(co8);
            table.addCell(co9);
            table.addCell(co10);

            table.addCell(ca1);
            table.addCell(ca2);
            table.addCell(ca3);
            table.addCell(ca4);
            table.addCell(ca5);
            table.addCell(ca6);
            table.addCell(ca7);
            table.addCell(ca8);
            table.addCell(ca9);
            table.addCell(ca10);

            table.addCell(wr1);
            table.addCell(wr2);
            table.addCell(wr3);
            table.addCell(wr4);
            table.addCell(wr5);
            table.addCell(wr6);
            table.addCell(wr7);
            table.addCell(wr8);
            table.addCell(wr9);
            table.addCell(wr10);

            table.addCell(nr1);
            table.addCell(nr2);
            table.addCell(nr3);
            table.addCell(nr4);
            table.addCell(nr5);
            table.addCell(nr6);
            table.addCell(nr7);
            table.addCell(nr8);
            table.addCell(nr9);
            table.addCell(nr10);

            table.addCell(v1);
            table.addCell(v2);
            table.addCell(v3);
            table.addCell(v4);
            table.addCell(v5);
            table.addCell(v6);
            table.addCell(v7);
            table.addCell(v8);
            table.addCell(v9);
            table.addCell(v10);

            table.addCell(q1);
            table.addCell(q2);
            table.addCell(q3);
            table.addCell(q4);
            table.addCell(q5);
            table.addCell(q6);
            table.addCell(q7);
            table.addCell(q8);
            table.addCell(q9);
            table.addCell(q10);

            table.addCell(m1);
            table.addCell(m2);
            table.addCell(m3);
            table.addCell(m4);
            table.addCell(m5);
            table.addCell(m6);
            table.addCell(m7);
            table.addCell(m8);
            table.addCell(m9);
            table.addCell(m10);

            table.addCell(ed1);
            table.addCell(ed2);
            table.addCell(ed3);
            table.addCell(ed4);
            table.addCell(ed5);
            table.addCell(ed6);
            table.addCell(ed7);
            table.addCell(ed8);
            table.addCell(ed9);
            table.addCell(ed10);

            table.addCell(ve1);
            table.addCell(ve2);
            table.addCell(ve3);
            table.addCell(ve4);
            table.addCell(ve5);
            table.addCell(ve6);
            table.addCell(ve7);
            table.addCell(ve8);
            table.addCell(ve9);
            table.addCell(ve10);

            table.addCell(qu1);
            table.addCell(qu2);
            table.addCell(qu3);
            table.addCell(qu4);
            table.addCell(qu5);
            table.addCell(qu6);
            table.addCell(qu7);
            table.addCell(qu8);
            table.addCell(qu9);
            table.addCell(qu10);

            table.addCell(t1);
            table.addCell(t2);
            table.addCell(t3);
            table.addCell(t4);
            table.addCell(t5);
            table.addCell(t6);
            table.addCell(t7);
            table.addCell(t8);
            table.addCell(t9);
            table.addCell(t10);

            document.add(table);

            Paragraph rating = new Paragraph("KEY TO RATING: 5=EXCELLENT   4=GOOD   3=AVERAGE   2=BELLOW AVERAGE   1=POOR", cellfont);
            rating.setAlignment(Element.ALIGN_CENTER);
            document.add(rating);

            //Setting the width and spacing of the table
            PdfPTable table1 = new PdfPTable(12);
            table1.setWidthPercentage(105);
            table1.setSpacingBefore(8f);
            table1.setSpacingAfter(5f);

            //Setting the number of columns
            float[] colWidth1 = {4f, 0.3f, 0.3f, 0.3f, 0.3f, 0.3f, 4f, 0.3f, 0.3f, 0.3f, 0.3f, 0.3f};
            table1.setWidths(colWidth1);

            table1.addCell(new PdfPCell(new Phrase("CHARACTER DEVELOPMENT", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 5", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 4", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 3", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 2", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 1", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("   PRACTICAL SKILL", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 5", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 4", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 3", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 2", cellfont)));
            table1.addCell(new PdfPCell(new Phrase(" 1", cellfont)));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Education Drama", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Needle Work", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Cookery", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Public Speech", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Sports", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Musical memes", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            table1.addCell(new PdfPCell(new Phrase("Appearance", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("   Oral English", cellfont)));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));
            table1.addCell(new PdfPCell(new Phrase("")));

            document.add(table1);
            /* OSAIGBOVOMWAN VICTORY OSASOGIE */

            Paragraph credit = new Paragraph("", cellfont);
            credit.add("Number of credit(s) ____ Student Average marks: " + average_total + "                                                Class Average: ________");

            Paragraph remark = new Paragraph("", cellfont);
            remark.add("Class Teacher Remarks: ____________________________" + "                                   SCHOOL FEES:");
            remark.setSpacingBefore(3f);

            Paragraph sign = new Paragraph("", cellfont);
            sign.add("Signature: _______________________ Date: ___________" + "                                               Uniform: ________");
            sign.setSpacingBefore(3f);

            Paragraph principal = new Paragraph("", cellfont);
            principal.add("Principal's Remark: ________________________________" + "                                  Next Term Fees: ________");
            principal.setSpacingBefore(3f);

            Paragraph signs = new Paragraph("", cellfont);
            signs.add("Signature: _______________________ Date: ___________" + "                               Outstanding Fees: ________");
            signs.setSpacingBefore(3f);

            Paragraph explain = new Paragraph("", cellfont);
            explain.add("EXPLANATION OF REMARKS " + "                                                                             Other Fees: _____________");
            explain.setSpacingBefore(3f);

            Paragraph fail = new Paragraph("", cellfont);
            fail.add("28 - 39 FAIL         56 - 64 GOOD" + "                                                                    TOTAL: ____________________");
            fail.setSpacingBefore(3f);

            Paragraph pass = new Paragraph("", cellfont);
            pass.add("40 - 45 PASS       65 - 74 VERY GOOD");
            pass.setSpacingBefore(3f);

            Paragraph credits = new Paragraph("", cellfont);
            credits.add("48 - 55 CREDIT   75 - 100 EXCELLENT");
            credits.setSpacingBefore(3f);

            document.add(credit);
            document.add(remark);
            document.add(sign);
            document.add(principal);
            document.add(signs);
            document.add(explain);
            document.add(fail);
            document.add(pass);
            document.add(credits);

            JOptionPane.showMessageDialog(this, "Result saved");
            document.close();
            pdfWriter.close();

        } catch (DocumentException | FileNotFoundException e) {
            System.out.println(e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAgric;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtBS;
    private javax.swing.JTextField txtBT;
    private javax.swing.JTextField txtCRS;
    private javax.swing.JTextField txtCivic;
    public static javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtEdo;
    private javax.swing.JTextField txtEnglish;
    public static javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtICT;
    private javax.swing.JTextField txtMaths;
    private javax.swing.JTextField txtPHE;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtQuan;
    private javax.swing.JTextField txtSecurity;
    private javax.swing.JTextField txtSocial;
    public static javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtTotalScore;
    private javax.swing.JTextArea txtTranscript;
    private javax.swing.JTextField txtVerbal;
    // End of variables declaration//GEN-END:variables

    String getClassID;
    String getSchoolID;
    String getAdmClass;
    String getSname;
}
